import type { GameState, EngineMode, Settings } from './types';
import { getDefaultArchetype, type CampaignArchetype } from './archetypes';
import { formatCampaignStoryName } from '@/data/campaigns';
import { emptyWorldLedger } from './worldSim';
import { syncContainerOccupancy } from './inventory';

/** Bump this to retire every older local/cloud/Drive save after a playtest wipe. */
export const CURRENT_SAVE_VERSION = 2;

export function isPlayableSave(state: GameState | null | undefined): state is GameState {
  return !!state && typeof state.saveId === 'string' && (state.version ?? 0) >= CURRENT_SAVE_VERSION;
}

export function createInitialState(storyName?: string, engineMode: EngineMode = 'litrpg', archetype?: CampaignArchetype): GameState {
  const now = Date.now();
  const defaultStory = formatCampaignStoryName('New Campaign', new Date(now));
  return syncContainerOccupancy({
    version: CURRENT_SAVE_VERSION,
    saveId: crypto.randomUUID(),
    storyName: storyName || defaultStory,
    engineMode,
    campaignArchetype: archetype ?? getDefaultArchetype(engineMode),
    lastUpdated: now,
    character: {
      name: 'Unknown Survivor',
      level: 1,
      xp: 0,
      xpToNext: 300,
      hp: 24,
      maxHp: 24,
      mp: 12,
      maxMp: 12,
      sp: 20,
      maxSp: 20,
      attributes: { STR: 14, DEX: 12, CON: 14, INT: 12, WIS: 10, CHA: 10 },
      conditions: [],
      bio: 'Someone already living in this world when the story begins.',
      // Do not assume a human body or generic adventurer clothing. Character creation or a
      // later <visual-update> supplies the canonical physical description; image prompts
      // safely fall back to bio/name while it is empty.
      appearance: '',
    },
    inventory: [
      {
        id: 'starter-weapon',
        name: 'Worn Iron Shortsword',
        rarity: 'Common',
        quantity: 1,
        equipped: true,
        slot: 'Main Hand',
        containerId: 'starter-satchel',
        provenance: 'On you when you arrived',
        description: 'A nicked iron blade. 1d6 slashing. Worn but serviceable.',
        itemType: 'weapon',
        modifiers: { STR: 1 },
      },
      {
        id: 'starter-armor',
        name: 'Patched Leather Tunic',
        rarity: 'Common',
        quantity: 1,
        equipped: true,
        slot: 'Body',
        containerId: 'starter-satchel',
        provenance: 'On you when you arrived',
        description: 'Scuffed leather. Better than a shirt.',
        itemType: 'armor',
        modifiers: { CON: 1 },
      },
      {
        id: 'starter-potion',
        name: 'Minor Healing Draught',
        rarity: 'Common',
        quantity: 3,
        containerId: 'starter-satchel',
        provenance: 'On you when you arrived',
        description: 'Restores 2d4+2 HP.',
      },
    ],
    containers: [
      { id: 'starter-satchel', name: 'Worn Satchel', capacity: 20, used: 3, modifier: 'none', itemIds: ['starter-weapon', 'starter-armor', 'starter-potion'], storageType: 'General', kind: 'physical', equipped: true, slot: 'Container' },
    ],
    materials: [],
    companions: [],
    quests: [],
    shrines: [],
    bestiary: [],
    relationships: [],
    log: [
      {
        id: 'intro-1',
        turn: 0,
        role: 'system',
        content: 'New journey initialized. Configure your character in Settings, or begin play.',
        timestamp: Date.now(),
      },
    ],
    rolls: [],
    turn: 0,
    seed: Math.random().toString(36).slice(2, 10),
    pendingImagePrompt: null,
    lorebook: [],
    timeline: [],
    campaignBibleId: null,
    campaignPremise: null,
    npcMemories: [],
    locationSheet: null,
    previousLocationSheet: null,
    lootPity: { byTier: {} },
    tutorialProgress: {
      completed: {},
      firstChestUncommonBiasPending: true,
      fullStatusUnlocked: false,
      stickyFailScheduled: false,
    },
    places: [],
    campaignMemory: {
      campaignSummary: null,
      personalitySummary: null,
      turnSummaries: [],
      pins: [],
      consequences: [],
      lastCampaignSummaryTurn: 0,
      lastTurnSummaryTurn: 0,
    },
    statusReveal: 'minimal',
    pendingTurn: null,
    gold: 0,
    worldLedger: emptyWorldLedger(),
    gmStrictness: 'standard',
    statDisplayMode: 'inline',
    turnFrameTheme: { icon: '🎲', accentColor: 'cyan-400', frameStyle: 'minimal-holo' },
    currentCoordinates: { q: 0, r: 0, tier: 2, z: 0 },
    activeEncounter: null,
  });
}

export function createDefaultSettings(): Settings {
  return {
    ttsEnabled: false,
    sttEnabled: false,
    diceAnimation: 'visual',
    contentMode: 'adult',
    kidModeLocked: false,
    contentPin: null,
    maturityTier: 'pg13',
    sexualContent: false,
    substanceUse: true,
    darkThemes: 'implied',
    confirmContentRewrites: true,
    geminiApiKey: '',
    openrouterApiKey: '',
    aiProvider: 'gemini',
    customModelId: '',
    baseUrl: '',
    imageProvider: 'gemini',
    imageBaseUrl: '',
    imageApiKey: '',
    imageEndpointType: 'openai',
    imageModel: '',
    videoProvider: 'none',
    videoBaseUrl: '',
    videoApiKey: '',
    videoModel: '',
    postLoginBehavior: 'MAIN_MENU',
    visualMode: 'comic',
    classicMemorableImages: false,
    comicLayout: 'paged',
    comicReadingDirection: 'ltr',
    bgMode: 'static',
    bgOpacity: 40,
    artStylePreset: 'classic-book',
    colorVariant: 'default',
    panelFrequency: 'balanced',
    halftoneOverlay: true,
    sfxPopups: true,
    speechBubbles: true,
    panelBorderIntensity: 'bold',
    gmStrictness: 'standard',
    statDisplayMode: 'inline',
    statVerbosity: 'core',
    statFrequency: 'every-5-turns',
    perspective: 'second-person',
    violenceLevel: 'mild',
    cursingLevel: 'mild',
    romanceSubplots: false,
    haremContent: false,
    statScreensEnabled: true,
    dndMode: false,
    mapTriggerMode: 'tactical',
    fogRevealThreshold: 'adjacent',
    combatFrequency: 50,
    socialRoleplay: 50,
    worldBuilding: 50,
    strictEncumbrance: false,
    requireTurnConfirm: false,
    secretDeathSaves: false,
    cleaveMechanics: false,
    flankingAdvantage: false,
  };
}