import type { GameState, EngineMode, Settings } from './types';
import { getDefaultArchetype, type CampaignArchetype } from './archetypes';

export function createInitialState(storyName?: string, engineMode: EngineMode = 'litrpg', archetype?: CampaignArchetype): GameState {
  const now = Date.now();
  const defaultStory = `Campaign - ${new Date(now).toLocaleDateString()}`;
  return {
    version: 1,
    saveId: crypto.randomUUID(),
    storyName: storyName || defaultStory,
    engineMode,
    campaignArchetype: archetype ?? getDefaultArchetype(engineMode),
    lastUpdated: now,
    character: {
      name: 'Unknown Survivor',
      level: 1,
      xp: 0,
      xpToNext: 300,
      hp: 24,
      maxHp: 24,
      mp: 12,
      maxMp: 12,
      sp: 20,
      maxSp: 20,
      attributes: { STR: 14, DEX: 12, CON: 14, INT: 12, WIS: 10, CHA: 10 },
      conditions: [],
      bio: 'A transmigrated soul, newly arrived in an unfamiliar world with no local knowledge.',
      // Do not assume a human body or generic adventurer clothing. Character creation or a
      // later <visual-update> supplies the canonical physical description; image prompts
      // safely fall back to bio/name while it is empty.
      appearance: '',
    },
    inventory: [
      {
        id: 'starter-weapon',
        name: 'Worn Iron Shortsword',
        rarity: 'Common',
        quantity: 1,
        equipped: true,
        slot: 'Main Hand',
        provenance: 'Found on arrival',
        modifiers: { STR: 1 },
      },
      {
        id: 'starter-armor',
        name: 'Patched Leather Tunic',
        rarity: 'Common',
        quantity: 1,
        equipped: true,
        slot: 'Body',
        provenance: 'Found on arrival',
        modifiers: { CON: 1 },
      },
      {
        id: 'starter-potion',
        name: 'Minor Healing Draught',
        rarity: 'Common',
        quantity: 3,
        provenance: 'Found on arrival',
        description: 'Restores 2d4+2 HP.',
      },
    ],
    containers: [
      { id: 'spatial-bag', name: 'Spatial Pouch', capacity: 20, used: 3, modifier: 'none', itemIds: [], storageType: 'General', kind: 'magical', equipped: true, slot: 'Container' },
    ],
    materials: [],
    companions: [],
    quests: [],
    shrines: [],
    bestiary: [],
    relationships: [],
    log: [
      {
        id: 'intro-1',
        turn: 0,
        role: 'system',
        content: 'New journey initialized. Configure your character in Settings, or begin play.',
        timestamp: Date.now(),
      },
    ],
    rolls: [],
    turn: 0,
    seed: Math.random().toString(36).slice(2, 10),
    pendingImagePrompt: null,
    lorebook: [],
    gold: 0,
    gmStrictness: 'standard',
    statDisplayMode: 'inline',
    turnFrameTheme: { icon: '🎲', accentColor: 'cyan-400', frameStyle: 'minimal-holo' },
    currentCoordinates: { q: 0, r: 0, tier: 2, z: 0 },
    activeEncounter: null,
  };
}

export function createDefaultSettings(): Settings {
  return {
    ttsEnabled: false,
    sttEnabled: false,
    diceAnimation: 'visual',
    contentMode: 'adult',
    kidModeLocked: false,
    contentPin: null,
    geminiApiKey: '',
    openrouterApiKey: '',
    aiProvider: 'gemini',
    customModelId: '',
    baseUrl: '',
    imageProvider: 'gemini',
    imageBaseUrl: '',
    imageApiKey: '',
    imageEndpointType: 'openai',
    imageModel: '',
    videoProvider: 'none',
    videoBaseUrl: '',
    videoApiKey: '',
    videoModel: '',
    postLoginBehavior: 'MAIN_MENU',
    visualMode: 'comic',
    classicMemorableImages: false,
    comicLayout: 'paged',
    comicReadingDirection: 'ltr',
    bgMode: 'static',
    bgOpacity: 40,
    artStylePreset: 'classic-book',
    colorVariant: 'default',
    panelFrequency: 'balanced',
    halftoneOverlay: true,
    sfxPopups: true,
    speechBubbles: true,
    panelBorderIntensity: 'bold',
    gmStrictness: 'standard',
    statDisplayMode: 'inline',
    statVerbosity: 'core',
    statFrequency: 'every-5-turns',
    perspective: 'third-person',
    violenceLevel: 'mild',
    cursingLevel: 'mild',
    romanceSubplots: false,
    haremContent: false,
    statScreensEnabled: true,
    dndMode: false,
    mapTriggerMode: 'tactical',
    fogRevealThreshold: 'adjacent',
    combatFrequency: 50,
    socialRoleplay: 50,
    worldBuilding: 50,
    strictEncumbrance: false,
    secretDeathSaves: false,
    cleaveMechanics: false,
    flankingAdvantage: false,
  };
}