#!/usr/bin/env python3
import csv
from pathlib import Path

root = Path('/home/ubuntu/SynapticGM_mega_research_pack_2026-08-25')
viewports = [
    ('desktop', 1440, 900),
    ('mobile', 390, 844),
]

cases = [
('A01','P0','New Game theme picker','New Game / Theme','Fresh signed-in test account; standard mode','fixture:new_game_clean','Open New Game; open Theme; do not choose a theme.','Theme selector opens without altering GameState; live approved theme list is present; default and custom choices are understandable.','Retired world names; licensed titles; clipped controls; theme change before confirmation; horizontal page overflow.','Redact account email.'),
('A02','P0','Official and custom theme labels','New Game / Theme','Theme picker open','fixture:theme_labels','Capture Default, a shipped official theme, Custom, and random picker in one frame or documented scroll set.','Labels distinguish official shipped themes from user custom input without claiming endorsement or licence for user text.','An official label on arbitrary user text; missing Custom path; retired strings; hidden random behaviour.','Redact account email.'),
('A03','P0','Kid Mode prompt filtering','New Game / Kid Mode','Kid Mode enabled before theme/prompt selection','fixture:kid_mode_clean','Enable Kid Mode; open every visible prompt category; capture the filtered state.','No adult rows, sexualized wording, graphic injury, gambling, alcohol focus, or ad entry point is visible.','Any adult row; ad prompt; frightening repair language; safety label without actual filtering.','Use synthetic account only.'),
('A04','P1','Custom opening prompt boundary','New Game / Custom prompt','Standard mode; custom prompt field empty','fixture:custom_prompt','Type a generic original premise; capture before submission.','Prompt helper requests original description and avoids suggesting franchises, creators, studios, or brands.','“Write like” examples; licensed title autocomplete; real-person style cue; unsupported guaranteed memory claim.','Use only synthetic prompt text.'),
('A05','P0','First GM page grounding','Game / opening turn','New game created from a known fixture','fixture:opener_grounded_adult','Generate the first page; capture the full opening and final choice-pressure question.','Only fixture facts are asserted; flair stays sensory; adult viewpoint; no chip/menu prose inside narrative; no licensed or retired terms.','Invented item/person/rank; child viewpoint; forced choice; implementation jargon; franchise reference.','Use a synthetic character biography.'),
('A06','P0','Accepted quest provenance','Game / Quest ledger','Fixture with explicit player acceptance','fixture:quest_accepted','Open quest ledger immediately after acceptance.','Accepted state cites the accepting act/turn; objective is not marked completed; status is visibly different from rumor and open offer.','Acceptance inferred from hearing; missing provenance; rumor shown as accepted; unreadable mobile state.','Synthetic names only.'),
('A07','P0','Rumor provenance','Game / Quest ledger','Fixture where player only hears a rumor','fixture:quest_rumor','Open quest ledger after the rumor turn.','Entry is labeled or worded as rumor; no commitment, reward, or completion state is implied.','Active quest badge; accepted wording; invented objective details; speaker not present in source turn.','Synthetic names only.'),
('A08','P0','Soft offer provenance','Game / Quest ledger','Fixture with offer and no response','fixture:quest_soft_offer','Open quest ledger after offer but before acceptance/decline.','Offer remains open and visibly non-accepted; both engage and leave paths remain available.','Accepted state; countdown not in fixture; coercive copy; hidden decline path.','Synthetic names only.'),
('A09','P0','Object-in-hand repair','Game / Repair banner','Fixture output claims an absent held object','fixture:repair_invented_item','Trigger the known adversarial output; capture banner and corrected scene.','Unsupported item is removed; valid player action and surrounding prose remain; correction uses ordinary story language.','Item remains; whole turn erased; player blamed; model/regex/validation jargon.','Synthetic inventory.'),
('A10','P0','Absent companion repair','Game / Repair banner','Fixture calls an absent companion into scene','fixture:repair_absent_companion','Trigger and capture standard-mode repair plus corrected scene.','Companion is removed/restored to prior location; action persists; banner is concise.','Companion speaks or acts; history rewritten; unrelated details change.','Synthetic names only.'),
('A11','P0','Ungrounded talk repair','Game / Repair banner','Fixture makes a location or absent source speak','fixture:repair_ungrounded_talk','Trigger and capture repair plus corrected exchange.','Unsupported line is removed or assigned only to a grounded present source; no implementation jargon.','Wall/location still speaks; absent person quoted as live; valid narration deleted.','Synthetic content.'),
('A12','P0','Cancel and restore','Game / Cancel action','Fixture with reversible pending action','fixture:cancel_restore','Start action; use Cancel; capture restored state and confirmation.','Prior completed moment, position, inventory, and cap are restored according to product rule.','Cancelled consequence remains; duplicate item; turn consumed incorrectly; ambiguous status.','Synthetic content.'),
('A13','P1','Why line disclosure','Game / Why? panel','A continuity check has fired','fixture:why_line','Open Why? from the check or repair surface.','One short plain-language reason names what was checked without revealing technical internals.','Model, prompt, regex, retrieval, transaction, validator, or hidden chain-of-thought wording.','No real user content.'),
('A14','P0','Correction confirmation','Game / confirmation','A repair has completed','fixture:correction_confirmed','Capture the post-repair confirmation and first unchanged surrounding paragraph.','Confirmation says what category was corrected; valid choice and unaffected facts visibly persist.','Claims all memory is perfect; vague apology only; changed unrelated facts.','Synthetic content.'),
('A15','P1','Changed status chip','Game / STATUS','Fixture with one confirmed state change','fixture:status_chip_changed','Capture the status chip beside the resulting scene.','Chip is eight words or fewer, names the confirmed change, and is readable at both widths.','More than eight words; hidden overflow; unsupported change; implementation jargon.','Synthetic content.'),
('A16','P0','Bound relic identification','Inventory / relic detail','Relic present but unbound and identified','fixture:relic_identified','Open item detail before binding.','Exact relic instance, candidate skill, cost, tell, and use conditions are visible before commitment.','Skill already owned; hidden cost; generic item type rather than instance; automatic binding.','Synthetic relic.'),
('A17','P0','Bound relic commitment','Inventory / bind confirmation','Identified relic; no bond','fixture:relic_bind','Open Bind confirmation without accepting.','Confirmation names exact object and disclosed cost; Cancel and Bind are distinct and accessible.','Preselected hidden consent; surprise cost; no cancel; coercive destiny copy.','Synthetic relic.'),
('A18','P0','Bound relic dormant state','Skills / bound relic','Previously bound relic moved out of possession','fixture:relic_dormant','Move relic to storage using fixture; open skill detail.','Skill history remains; status is dormant/unavailable with grounded source reason; another copy does not inherit bond.','Skill silently deleted; skill still active; duplicate copy shown as bound; provenance lost.','Synthetic relic.'),
('A19','P0','Readable/codex study','Inventory / readable detail','Readable source acquired; no study progress','fixture:codex_readable','Open source detail and begin study preview.','Readability, candidate skill, requirements, time/opportunity cost, and progress state are distinct.','Instant mastery on ownership; unreadable source teaches; hidden requirement.','Synthetic book/manual.'),
('A20','P0','Codex learn commitment','Skills / commit','Study ready; skill not learned','fixture:codex_commit','Open Learn confirmation before accepting.','Named skill, source, slot/trade-off if any, and durability are shown before commitment.','Auto-learn; arbitrary skill selection; source provenance absent.','Synthetic source.'),
('A21','P0','Deed-derived skill offer','Game / skill offer','Confirmed deed creates one pending offer','fixture:deed_offer','Complete deed fixture; capture offer panel.','Panel says “Because you…” with factual deed summary; named skill; terms; Accept and Decline; no auto-grant.','Invented motive/rank; skill already added; decline hidden; story blocked until accept.','Synthetic deed.'),
('A22','P0','Decline persists','Skill offer history','Previously declined offer; page reloaded','fixture:deed_declined','Decline; reload; advance one turn; open offer history.','Offer remains declined, skill absent, story continues, and same offer is not active again.','Offer reappears; skill granted; guilt/shame copy; refusal history missing.','Synthetic deed.'),
('A23','P0','Free remaining-turn counter','Game / cap meter','Free account with known remaining count','fixture:cap_remaining_3','Open game before an action and capture meter/help.','Exact remaining count comes from fixture; refresh wording is honest; no ad pressure in main action.','Approximate UI when exact counter exists; false reset time; hidden allowance.','Redact account identifier.'),
('A24','P0','Free cap reached','Game / cap reached','Free account at zero remaining','fixture:cap_zero','Open action composer and cap explanation.','Story is saved if verified; next refresh is stated only if authoritative; no forced ad; paid option not disguised.','Composer submits paid call; fake countdown; forced ad; lost story claim without evidence.','Redact account identifier.'),
('A25','P0','Failed-turn cap refund','Game / failure recovery','Free account; deterministic no-result failure fixture','fixture:failed_turn_refund','Record counter before; trigger failure; capture refund confirmation and restored counter.','Turn returns exactly once; scene remains at last completed moment; retry is available.','Cap remains consumed; double refund; partial state change persists; provider billing exposed to player.','Synthetic content; redact account identifier.'),
('A26','P0','One-time New Game +8','New Game / cap confirmation','Free account eligible for one-time opening bonus','fixture:new_game_bonus','Create New Game; capture bonus confirmation; reload and capture already-used state if one image can show history.','Eight extra text turns added once; durable state prevents duplicate grant; wording does not imply infinite restarts.','Repeated grant; missing count; bonus consumes base turn; misleading expiry.','Redact account identifier.'),
('A27','P0','Optional ad overflow standard mode','Post-scene overflow','Standard mode; base allowance exhausted; approved test ad stub','fixture:ad_overflow_standard','Finish a scene; open optional overflow after the result.','Offer is after scene, optional, states extra turns, offers No thanks, and leaves base allowance unchanged.','Ad mid-action; forced viewing; hidden reward; story influence claim; pre-result interstitial.','Use non-production test ad; redact ad IDs.'),
('A28','P0','No ad in Kid Mode','Kid Mode / network and UI','Kid Mode; same cap condition as A27','fixture:ad_absent_kid','Open cap/overflow surfaces and capture UI; attach network evidence separately.','No ad UI, prompt, placeholder, SDK consent, or reward path exists in Kid Mode.','Any ad affordance; disabled teaser; SDK call; identifier creation; “ask an adult to watch” nudge.','Use synthetic child-safe account; redact identifiers.'),
('A29','P0','Memorable generation default OFF','Settings / memorable','Free account; fresh game','fixture:memorable_off_free','Open relevant setting/plan detail and a memorable moment surface.','Default is OFF; Free shows zero weekly entitlement; no automatic generation request or loading state.','Auto-call; emotional nudge; hidden cost; weekly entitlement above zero.','Redact account identifier.'),
('A30','P1','Map chrome continuity','Map view','Fixture with shipped parchment/topographic assets','fixture:map_original_assets','Open map at default zoom; capture chrome and one floor-plan fill.','Existing original parchment/topographic assets remain primary; decorative fills do not invent exits, labels, or measured elevation.','Real-world map; readable accidental text; franchise symbol; decorative route presented as fact.','Synthetic place names or no readable names.'),
('A31','P1','Memorable plate adult viewpoint','Memorable image preview','Eligible standard-mode adult biography; test image fixture','fixture:plate_adult','Open the generated/approved plate preview with source-moment summary.','Adult-scale viewpoint; confirmed people/items/weather; ink-and-watercolour book plate; no text/logo/signature.','Child proportions; invented companion/item; readable text; named-style imitation; graphic gore.','Synthetic biography; no real face.'),
('A32','P0','Kid-safe memorable plate','Memorable image preview','Kid Mode; eligible child-safe fixture only','fixture:plate_kid_safe','Open approved Kid Mode plate and source summary.','No sexualized framing, graphic injury, alcohol/gambling focus, frightening body horror, text/logo, or ad adjacency.','Any unsafe focal content; adult plate reused without safety review; unsupported child viewpoint.','Synthetic biography; no real face.'),
('A33','P0','No implementation jargon in error path','Game / error and repair surfaces','Failure, repair, and retry fixtures available','fixture:no_jargon','Capture the most technical player-facing failure and repair states.','Copy uses ordinary story/service language; internal IDs and mechanics are hidden.','LLM, AI model, regex, retrieval, transaction, validator, system prompt, hallucination, stack trace.','Redact request/error IDs.'),
('A34','P1','Asset intake licence view','Founder/admin asset intake','Internal admin/founder access; one CC0 and one MIT record','fixture:asset_intake','Open CC0 item then MIT item; capture source/licence/provenance fields.','Licence, source page, direct download, retrieval date, provenance, and notice obligation are explicit; status is not legal certainty.','Missing source; MIT notice omitted; scrape/proxy URL; share-alike item marked default YES.','Redact private admin/account data.'),
('A35','P0','Share-alike excluded by default','Founder/admin asset intake','Internal admin; share-alike risk fixture','fixture:share_alike_excluded','Open risk record and any add-to-project control.','Default is counsel review/excluded; not available in player picker or shipped asset set.','One-click default inclusion; missing reciprocal-duty warning; no provenance.','Redact private admin/account data.'),
('A36','P0','Responsive trust surfaces','Game / combined trust state','Fixture showing status chip, Why?, repair, and action composer','fixture:responsive_trust','Capture full viewport without browser zoom changes.','No horizontal page overflow; controls remain reachable; text wraps; focus/order is coherent; action composer not obscured.','Overlapping banners; clipped buttons; off-screen close/decline; unreadable chip; fixed element covers result.','Synthetic content.'),
]

fields = ['audit_id','priority','feature','surface','viewport','width','height','preconditions','seed_or_fixture','capture_steps','pass_cues','fail_cues','redaction','expected_filename','status','owner','evidence_path','notes']
rows=[]
for case in cases:
    base_id, priority, feature, surface, preconditions, fixture, steps, passes, fails, redaction = case
    for viewport, width, height in viewports:
        rows.append({
            'audit_id': f'{base_id}-{viewport.upper()}',
            'priority': priority,
            'feature': feature,
            'surface': surface,
            'viewport': viewport,
            'width': width,
            'height': height,
            'preconditions': preconditions,
            'seed_or_fixture': fixture,
            'capture_steps': steps,
            'pass_cues': passes,
            'fail_cues': fails,
            'redaction': redaction,
            'expected_filename': f'{base_id.lower()}_{viewport}_{width}x{height}.png',
            'status': 'NOT RUN',
            'owner': 'INPUT REQUIRED',
            'evidence_path': 'INPUT REQUIRED',
            'notes': 'Capture at 100% browser zoom. Use a clean deterministic fixture and record build/commit, browser, date, and environment in the playbook run header.'
        })

out = root / 'audit_tracker.csv'
with out.open('w', newline='', encoding='utf-8') as f:
    w = csv.DictWriter(f, fieldnames=fields)
    w.writeheader(); w.writerows(rows)
assert len(rows) == len(cases) * 2 == 72
print(out)
