import type { ZoneSlice } from '../../types';

export const BRINEWATCH: ZoneSlice = {
  places: [
    {
      id: 'poi_brinewatch_dock',
      name: 'Brinewatch Dock',
      zoneId: 'brinewatch',
      mapScale: 'street',
      dangerTier: 'safe',
      outdoor: true,
      exits: ['poi_tidal_flats', 'poi_covenant_hall', 'poi_drying_racks'],
      npcIds: ['npc_tide_reader_nesh'],
    },
    {
      id: 'poi_coil_pier',
      name: 'Coil Pier',
      zoneId: 'brinewatch',
      mapScale: 'street',
      dangerTier: 'safe',
      outdoor: true,
      exits: ['poi_drying_racks', 'poi_stilt_walk'],
      npcIds: [],
    },
    {
      id: 'poi_tidal_flats',
      name: 'Tidal Flats',
      zoneId: 'brinewatch',
      mapScale: 'street',
      dangerTier: 'low',
      outdoor: true,
      exits: ['poi_brinewatch_dock', 'poi_stilt_walk', 'poi_flood_store'],
      npcIds: [],
    },
    {
      id: 'poi_covenant_hall',
      name: 'Covenant Hall',
      zoneId: 'brinewatch',
      mapScale: 'dungeon',
      dangerTier: 'safe',
      outdoor: false,
      exits: ['poi_brinewatch_dock'],
      npcIds: ['npc_hall_voice'],
    },
    {
      id: 'poi_drying_racks',
      name: 'Drying Racks',
      zoneId: 'brinewatch',
      mapScale: 'street',
      dangerTier: 'safe',
      outdoor: true,
      exits: ['poi_brinewatch_dock', 'poi_coil_pier'],
      npcIds: ['npc_fisher_pell'],
    },
    {
      id: 'poi_stilt_walk',
      name: 'Stilt Walk',
      zoneId: 'brinewatch',
      mapScale: 'street',
      dangerTier: 'low',
      outdoor: true,
      exits: ['poi_tidal_flats', 'poi_coil_pier', 'poi_flood_store'],
      npcIds: [],
    },
    {
      id: 'poi_flood_store',
      name: 'Flood Store',
      zoneId: 'brinewatch',
      mapScale: 'street',
      dangerTier: 'medium',
      outdoor: true,
      exits: ['poi_tidal_flats', 'poi_stilt_walk'],
      npcIds: [],
      dungeonId: 'dungeon_coil_warehouse',
    },
  ],
  npcs: [
    { id: 'npc_tide_reader_nesh', name: 'Tide-reader Nesh', placeId: 'poi_brinewatch_dock', role: 'quest', durable: true },
    { id: 'npc_fisher_pell', name: 'Fisher Pell', placeId: 'poi_drying_racks', role: 'profession', durable: true },
    { id: 'npc_hall_voice', name: 'Hall Voice Orin', placeId: 'poi_covenant_hall', role: 'hub', durable: true },
  ],
  species: [
    { id: 'species_brine_eel', name: 'Brine Eel', rarity: 'common', habitatTags: ['brinewatch'], baseHp: 14, baseAtk: 5, ac: 11 },
    { id: 'species_stilt_crab', name: 'Stilt Crab', rarity: 'common', habitatTags: ['brinewatch'], baseHp: 16, baseAtk: 4, ac: 13 },
    { id: 'species_tide_gnat', name: 'Tide Gnat', rarity: 'common', habitatTags: ['brinewatch'], baseHp: 6, baseAtk: 2, ac: 12 },
    { id: 'species_flat_runner', name: 'Flat Runner', rarity: 'uncommon', habitatTags: ['brinewatch'], baseHp: 36, baseAtk: 10, ac: 12 },
    { id: 'species_coil_leech', name: 'Coil Leech', rarity: 'uncommon', habitatTags: ['brinewatch'], baseHp: 28, baseAtk: 11, ac: 11 },
    { id: 'species_warehouse_warden', name: 'Warehouse Warden', rarity: 'epic', habitatTags: ['brinewatch'], baseHp: 190, baseAtk: 23, ac: 14 },
  ],
  items: [
    { id: 'item_iron_hatchet', name: 'Iron Hatchet', category: 'weapon', goldValue: 8, repairCostPerPoint: 0.5 },
    { id: 'item_brinewatch_map', name: 'Brinewatch Map', category: 'key', goldValue: 0, repairCostPerPoint: 0 },
    { id: 'item_eel_skin', name: 'Eel Skin', category: 'material', goldValue: 2, repairCostPerPoint: 0 },
    { id: 'item_dried_catch', name: 'Dried Catch', category: 'material', goldValue: 1, repairCostPerPoint: 0 },
    { id: 'item_tide_mark', name: 'Tide Mark', category: 'material', goldValue: 3, repairCostPerPoint: 0 },
    { id: 'item_coil_hook', name: 'Coil Hook', category: 'tool', goldValue: 5, repairCostPerPoint: 0 },
  ],
  quests: [
    {
      id: 'quest_saltkin_race_1',
      title: 'The Flats Are Wrong',
      family: 'race',
      hidden: false,
      unlocksQuestId: 'quest_saltkin_race_2',
      rewardGold: 100,
      rewardXp: 50,
      objectives: [
        { id: 'visit_flats', kind: 'visit_place', placeId: 'poi_tidal_flats' },
        { id: 'kill_eels', kind: 'ledger_kill', speciesId: 'species_brine_eel', count: 3 },
        { id: 'deliver_skin', kind: 'deliver_item', itemId: 'item_eel_skin', npcId: 'npc_tide_reader_nesh' },
      ],
    },
    {
      id: 'quest_saltkin_race_2',
      title: 'Runners Off the Tide',
      family: 'race',
      hidden: false,
      unlocksQuestId: 'quest_saltkin_race_3',
      rewardGold: 200,
      rewardXp: 100,
      objectives: [
        { id: 'visit_stilt', kind: 'visit_place', placeId: 'poi_stilt_walk' },
        { id: 'kill_runner', kind: 'ledger_kill', speciesId: 'species_flat_runner', count: 1 },
        { id: 'talk_nesh', kind: 'talk_to_npc', npcId: 'npc_tide_reader_nesh' },
      ],
    },
    {
      id: 'quest_saltkin_race_3',
      title: "Nesh's Mark",
      family: 'race',
      hidden: true,
      unlocksQuestId: null,
      rewardGold: 500,
      rewardXp: 300,
      objectives: [
        { id: 'collect_marks', kind: 'collect_item', itemId: 'item_tide_mark', count: 5 },
        { id: 'deliver_marks', kind: 'deliver_item', itemId: 'item_tide_mark', npcId: 'npc_tide_reader_nesh' },
      ],
    },
    {
      id: 'quest_fisher_1',
      title: 'Apprentice Fisher',
      family: 'profession',
      hidden: false,
      unlocksQuestId: 'quest_fisher_2',
      rewardGold: 50,
      rewardXp: 20,
      objectives: [
        { id: 'collect_catch', kind: 'collect_item', itemId: 'item_dried_catch', count: 8 },
        { id: 'deliver_catch', kind: 'deliver_item', itemId: 'item_dried_catch', npcId: 'npc_fisher_pell' },
      ],
    },
    {
      id: 'quest_fisher_2',
      title: 'Journeyman Fisher',
      family: 'profession',
      hidden: false,
      unlocksQuestId: 'quest_fisher_3',
      rewardGold: 150,
      rewardXp: 60,
      objectives: [
        { id: 'visit_racks', kind: 'visit_place', placeId: 'poi_drying_racks' },
        { id: 'kill_crabs', kind: 'ledger_kill', speciesId: 'species_stilt_crab', count: 5 },
        { id: 'collect_hook', kind: 'collect_item', itemId: 'item_coil_hook', count: 1 },
      ],
    },
    {
      id: 'quest_fisher_3',
      title: 'Master Fisher',
      family: 'profession',
      hidden: false,
      unlocksQuestId: null,
      rewardGold: 500,
      rewardXp: 120,
      objectives: [
        { id: 'collect_marks2', kind: 'collect_item', itemId: 'item_tide_mark', count: 4 },
        { id: 'deliver_hook', kind: 'deliver_item', itemId: 'item_coil_hook', npcId: 'npc_fisher_pell' },
      ],
    },
    {
      id: 'quest_brinewatch_zone_1',
      title: 'Water in the Store',
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: 'quest_brinewatch_zone_2',
      rewardGold: 75,
      rewardXp: 40,
      objectives: [
        { id: 'visit_hall', kind: 'visit_place', placeId: 'poi_covenant_hall' },
        { id: 'talk_orin', kind: 'talk_to_npc', npcId: 'npc_hall_voice' },
      ],
    },
    {
      id: 'quest_brinewatch_zone_2',
      title: 'Leeches on the Stilts',
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: 'quest_brinewatch_zone_3',
      rewardGold: 150,
      rewardXp: 100,
      objectives: [
        { id: 'visit_stilt2', kind: 'visit_place', placeId: 'poi_stilt_walk' },
        { id: 'kill_leech', kind: 'ledger_kill', speciesId: 'species_coil_leech', count: 3 },
      ],
    },
    {
      id: 'quest_brinewatch_zone_3',
      title: 'Clear the Flood Store',
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: null,
      rewardGold: 300,
      rewardXp: 200,
      objectives: [
        { id: 'visit_store', kind: 'visit_place', placeId: 'poi_flood_store' },
        { id: 'kill_warden', kind: 'ledger_kill', speciesId: 'species_warehouse_warden', count: 1 },
        { id: 'talk_nesh2', kind: 'talk_to_npc', npcId: 'npc_tide_reader_nesh' },
      ],
    },
  ],
  dungeons: [
    {
      id: 'dungeon_coil_warehouse',
      name: 'Coil Warehouse',
      entrancePlaceId: 'poi_flood_store',
      soloable: true,
      rooms: [
        { id: 'cw_door', name: 'Wet Door', describeBeforeCreature: true, encounter: null, isBoss: false, isCheckpoint: true, exits: ['cw_aisle'] },
        {
          id: 'cw_aisle',
          name: 'Flooded Aisle',
          describeBeforeCreature: true,
          encounter: [{ speciesId: 'species_brine_eel', count: 3 }],
          isBoss: false,
          isCheckpoint: false,
          exits: ['cw_hold'],
        },
        {
          id: 'cw_hold',
          name: 'Low Hold',
          describeBeforeCreature: true,
          encounter: [
            { speciesId: 'species_stilt_crab', count: 2 },
            { speciesId: 'species_coil_leech', count: 1, elite: true },
          ],
          isBoss: false,
          isCheckpoint: true,
          exits: ['cw_choice'],
        },
        { id: 'cw_choice', name: 'Two Hatches', describeBeforeCreature: true, encounter: null, isBoss: false, isCheckpoint: false, exits: ['cw_boss'] },
        {
          id: 'cw_boss',
          name: 'Nesting Hold',
          describeBeforeCreature: true,
          encounter: [{ speciesId: 'species_warehouse_warden', count: 1 }],
          isBoss: true,
          isCheckpoint: false,
          exits: [],
        },
      ],
    },
  ],
};
