import type { ZoneSlice } from '../../types';

export const GRANITE_STAIR: ZoneSlice = {
  places: [
    {
      id: 'poi_anvil_gate',
      name: 'Anvil Gate',
      zoneId: 'granite_stair',
      mapScale: 'street',
      dangerTier: 'safe',
      outdoor: true,
      exits: ['poi_granite_stair', 'poi_oath_hall', 'poi_ore_siding'],
      npcIds: ['npc_stair_oath_kell'],
    },
    {
      id: 'poi_granite_stair',
      name: 'Granite Stair',
      zoneId: 'granite_stair',
      mapScale: 'street',
      dangerTier: 'low',
      outdoor: true,
      exits: ['poi_anvil_gate', 'poi_cut_face', 'poi_slag_run'],
      npcIds: [],
    },
    {
      id: 'poi_oath_hall',
      name: 'Oath Hall',
      zoneId: 'granite_stair',
      mapScale: 'dungeon',
      dangerTier: 'safe',
      outdoor: false,
      exits: ['poi_anvil_gate'],
      npcIds: ['npc_smith_vorr'],
    },
    {
      id: 'poi_ore_siding',
      name: 'Ore Siding',
      zoneId: 'granite_stair',
      mapScale: 'street',
      dangerTier: 'safe',
      outdoor: true,
      exits: ['poi_anvil_gate', 'poi_cut_face'],
      npcIds: ['npc_siding_rusk'],
    },
    {
      id: 'poi_cut_face',
      name: 'Cut Face',
      zoneId: 'granite_stair',
      mapScale: 'street',
      dangerTier: 'low',
      outdoor: true,
      exits: ['poi_granite_stair', 'poi_ore_siding', 'poi_hollow_stair'],
      npcIds: [],
    },
    {
      id: 'poi_slag_run',
      name: 'Slag Run',
      zoneId: 'granite_stair',
      mapScale: 'street',
      dangerTier: 'low',
      outdoor: true,
      exits: ['poi_granite_stair', 'poi_hollow_stair'],
      npcIds: [],
    },
    {
      id: 'poi_hollow_stair',
      name: 'Hollow Stair',
      zoneId: 'granite_stair',
      mapScale: 'street',
      dangerTier: 'medium',
      outdoor: true,
      exits: ['poi_cut_face', 'poi_slag_run'],
      npcIds: [],
      dungeonId: 'dungeon_anvil_deep',
    },
  ],
  npcs: [
    { id: 'npc_stair_oath_kell', name: 'Stair-oath Kell', placeId: 'poi_anvil_gate', role: 'quest', durable: true },
    { id: 'npc_smith_vorr', name: 'Smith Vorr', placeId: 'poi_oath_hall', role: 'profession', durable: true },
    { id: 'npc_siding_rusk', name: 'Siding Rusk', placeId: 'poi_ore_siding', role: 'local', durable: true },
  ],
  species: [
    { id: 'species_stair_mite', name: 'Stair Mite', rarity: 'common', habitatTags: ['granite_stair'], baseHp: 12, baseAtk: 4, ac: 12 },
    { id: 'species_slag_crawler', name: 'Slag Crawler', rarity: 'common', habitatTags: ['granite_stair'], baseHp: 16, baseAtk: 5, ac: 13 },
    { id: 'species_cut_bat', name: 'Cut Bat', rarity: 'common', habitatTags: ['granite_stair'], baseHp: 8, baseAtk: 4, ac: 12 },
    { id: 'species_ore_lurker', name: 'Ore Lurker', rarity: 'uncommon', habitatTags: ['granite_stair'], baseHp: 42, baseAtk: 11, ac: 13 },
    { id: 'species_oath_echo', name: 'Oath Echo', rarity: 'rare', habitatTags: ['granite_stair'], baseHp: 40, baseAtk: 14, ac: 12 },
    { id: 'species_anvil_warden', name: 'Anvil Warden', rarity: 'epic', habitatTags: ['granite_stair'], baseHp: 210, baseAtk: 24, ac: 15 },
  ],
  items: [
    { id: 'item_stone_maul', name: 'Stone Maul', category: 'weapon', goldValue: 8, repairCostPerPoint: 0.5 },
    { id: 'item_granite_map', name: 'Granite Stair Map', category: 'key', goldValue: 0, repairCostPerPoint: 0 },
    { id: 'item_cracked_oath', name: 'Cracked Oath-stone', category: 'material', goldValue: 2, repairCostPerPoint: 0 },
    { id: 'item_slag_chip', name: 'Slag Chip', category: 'material', goldValue: 1, repairCostPerPoint: 0 },
    { id: 'item_ore_sample', name: 'Ore Sample', category: 'material', goldValue: 3, repairCostPerPoint: 0 },
    { id: 'item_temper_bit', name: 'Temper Bit', category: 'material', goldValue: 5, repairCostPerPoint: 0 },
  ],
  quests: [
    {
      id: 'quest_stonevein_race_1',
      title: 'The Stair Has a Crack',
      family: 'race',
      hidden: false,
      unlocksQuestId: 'quest_stonevein_race_2',
      rewardGold: 100,
      rewardXp: 50,
      objectives: [
        { id: 'visit_stair', kind: 'visit_place', placeId: 'poi_granite_stair' },
        { id: 'kill_mites', kind: 'ledger_kill', speciesId: 'species_stair_mite', count: 3 },
        { id: 'deliver_oath', kind: 'deliver_item', itemId: 'item_cracked_oath', npcId: 'npc_stair_oath_kell' },
      ],
    },
    {
      id: 'quest_stonevein_race_2',
      title: 'Cut Face Listening',
      family: 'race',
      hidden: false,
      unlocksQuestId: 'quest_stonevein_race_3',
      rewardGold: 200,
      rewardXp: 100,
      objectives: [
        { id: 'visit_cut', kind: 'visit_place', placeId: 'poi_cut_face' },
        { id: 'kill_lurker', kind: 'ledger_kill', speciesId: 'species_ore_lurker', count: 1 },
        { id: 'talk_kell', kind: 'talk_to_npc', npcId: 'npc_stair_oath_kell' },
      ],
    },
    {
      id: 'quest_stonevein_race_3',
      title: "Kell's Oath",
      family: 'race',
      hidden: true,
      unlocksQuestId: null,
      rewardGold: 500,
      rewardXp: 300,
      objectives: [
        { id: 'collect_ore', kind: 'collect_item', itemId: 'item_ore_sample', count: 5 },
        { id: 'deliver_ore', kind: 'deliver_item', itemId: 'item_ore_sample', npcId: 'npc_stair_oath_kell' },
      ],
    },
    {
      id: 'quest_smith_1',
      title: 'Apprentice Smith',
      family: 'profession',
      hidden: false,
      unlocksQuestId: 'quest_smith_2',
      rewardGold: 50,
      rewardXp: 20,
      objectives: [
        { id: 'collect_slag', kind: 'collect_item', itemId: 'item_slag_chip', count: 8 },
        { id: 'deliver_slag', kind: 'deliver_item', itemId: 'item_slag_chip', npcId: 'npc_smith_vorr' },
      ],
    },
    {
      id: 'quest_smith_2',
      title: 'Journeyman Smith',
      family: 'profession',
      hidden: false,
      unlocksQuestId: 'quest_smith_3',
      rewardGold: 150,
      rewardXp: 60,
      objectives: [
        { id: 'visit_hall', kind: 'visit_place', placeId: 'poi_oath_hall' },
        { id: 'kill_crawlers', kind: 'ledger_kill', speciesId: 'species_slag_crawler', count: 5 },
        { id: 'collect_temper', kind: 'collect_item', itemId: 'item_temper_bit', count: 1 },
      ],
    },
    {
      id: 'quest_smith_3',
      title: 'Master Smith',
      family: 'profession',
      hidden: false,
      unlocksQuestId: null,
      rewardGold: 500,
      rewardXp: 120,
      objectives: [
        { id: 'collect_ore2', kind: 'collect_item', itemId: 'item_ore_sample', count: 4 },
        { id: 'deliver_temper', kind: 'deliver_item', itemId: 'item_temper_bit', npcId: 'npc_smith_vorr' },
      ],
    },
    {
      id: 'quest_granite_zone_1',
      title: 'Something Grinds Below',
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: 'quest_granite_zone_2',
      rewardGold: 75,
      rewardXp: 40,
      objectives: [
        { id: 'visit_siding', kind: 'visit_place', placeId: 'poi_ore_siding' },
        { id: 'talk_rusk', kind: 'talk_to_npc', npcId: 'npc_siding_rusk' },
      ],
    },
    {
      id: 'quest_granite_zone_2',
      title: 'Slag Run Echo',
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: 'quest_granite_zone_3',
      rewardGold: 150,
      rewardXp: 100,
      objectives: [
        { id: 'visit_slag', kind: 'visit_place', placeId: 'poi_slag_run' },
        { id: 'kill_echo', kind: 'ledger_kill', speciesId: 'species_oath_echo', count: 1 },
      ],
    },
    {
      id: 'quest_granite_zone_3',
      title: 'The Hollow Stair',
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: null,
      rewardGold: 300,
      rewardXp: 200,
      objectives: [
        { id: 'visit_hollow', kind: 'visit_place', placeId: 'poi_hollow_stair' },
        { id: 'kill_warden', kind: 'ledger_kill', speciesId: 'species_anvil_warden', count: 1 },
        { id: 'talk_kell2', kind: 'talk_to_npc', npcId: 'npc_stair_oath_kell' },
      ],
    },
  ],
  dungeons: [
    {
      id: 'dungeon_anvil_deep',
      name: 'Anvil Deep',
      entrancePlaceId: 'poi_hollow_stair',
      soloable: true,
      rooms: [
        { id: 'ad_lip', name: 'Stair Lip', describeBeforeCreature: true, encounter: null, isBoss: false, isCheckpoint: true, exits: ['ad_cut'] },
        {
          id: 'ad_cut',
          name: 'Mite Cut',
          describeBeforeCreature: true,
          encounter: [{ speciesId: 'species_stair_mite', count: 3 }],
          isBoss: false,
          isCheckpoint: false,
          exits: ['ad_slag'],
        },
        {
          id: 'ad_slag',
          name: 'Slag Chamber',
          describeBeforeCreature: true,
          encounter: [
            { speciesId: 'species_slag_crawler', count: 2 },
            { speciesId: 'species_ore_lurker', count: 1, elite: true },
          ],
          isBoss: false,
          isCheckpoint: true,
          exits: ['ad_choice'],
        },
        { id: 'ad_choice', name: 'Two Veins', describeBeforeCreature: true, encounter: null, isBoss: false, isCheckpoint: false, exits: ['ad_boss'] },
        {
          id: 'ad_boss',
          name: 'Deep Anvil',
          describeBeforeCreature: true,
          encounter: [{ speciesId: 'species_anvil_warden', count: 1 }],
          isBoss: true,
          isCheckpoint: false,
          exits: [],
        },
      ],
    },
  ],
};
