import type { ZoneSlice } from '../../types';

export const LAMPWOOD: ZoneSlice = {
  places: [
    {
      id: 'poi_wickhaven',
      name: 'Wickhaven',
      zoneId: 'lampwood',
      mapScale: 'street',
      dangerTier: 'safe',
      outdoor: true,
      exits: ['poi_lampwood_path', 'poi_wickhaven_loft', 'poi_ember_cut'],
      npcIds: ['npc_pathwarden_sila'],
    },
    {
      id: 'poi_lampwood_path',
      name: 'Lampwood Path',
      zoneId: 'lampwood',
      mapScale: 'street',
      dangerTier: 'low',
      outdoor: true,
      exits: ['poi_wickhaven', 'poi_unlit_bend', 'poi_watch_lantern'],
      npcIds: [],
    },
    {
      id: 'poi_wickhaven_loft',
      name: 'Wickhaven Loft',
      zoneId: 'lampwood',
      mapScale: 'dungeon',
      dangerTier: 'safe',
      outdoor: false,
      exits: ['poi_wickhaven'],
      npcIds: ['npc_wick_tender'],
    },
    {
      id: 'poi_ember_cut',
      name: 'Ember Cut',
      zoneId: 'lampwood',
      mapScale: 'street',
      dangerTier: 'safe',
      outdoor: true,
      exits: ['poi_wickhaven', 'poi_watch_lantern'],
      npcIds: ['npc_guide_brann'],
    },
    {
      id: 'poi_watch_lantern',
      name: 'Watch-Lantern',
      zoneId: 'lampwood',
      mapScale: 'street',
      dangerTier: 'low',
      outdoor: true,
      exits: ['poi_lampwood_path', 'poi_ember_cut', 'poi_hollow_mouth'],
      npcIds: [],
    },
    {
      id: 'poi_unlit_bend',
      name: 'Unlit Bend',
      zoneId: 'lampwood',
      mapScale: 'street',
      dangerTier: 'low',
      outdoor: true,
      exits: ['poi_lampwood_path', 'poi_hollow_mouth'],
      npcIds: [],
    },
    {
      id: 'poi_hollow_mouth',
      name: 'Hollow Mouth',
      zoneId: 'lampwood',
      mapScale: 'street',
      dangerTier: 'medium',
      outdoor: true,
      exits: ['poi_watch_lantern', 'poi_unlit_bend'],
      npcIds: [],
      dungeonId: 'dungeon_unlit_hollow',
    },
  ],
  npcs: [
    { id: 'npc_pathwarden_sila', name: 'Pathwarden Sila', placeId: 'poi_wickhaven', role: 'quest', durable: true },
    { id: 'npc_wick_tender', name: 'Wick Tender Cal', placeId: 'poi_wickhaven_loft', role: 'profession', durable: true },
    { id: 'npc_guide_brann', name: 'Guide Brann', placeId: 'poi_ember_cut', role: 'local', durable: true },
  ],
  species: [
    { id: 'species_path_moth', name: 'Path Moth', rarity: 'common', habitatTags: ['lampwood'], baseHp: 8, baseAtk: 4, ac: 11 },
    { id: 'species_shade_deer', name: 'Shade Deer', rarity: 'common', habitatTags: ['lampwood'], baseHp: 18, baseAtk: 6, ac: 11 },
    { id: 'species_wick_beetle', name: 'Wick Beetle', rarity: 'common', habitatTags: ['lampwood'], baseHp: 10, baseAtk: 3, ac: 12 },
    { id: 'species_unlit_sprout', name: 'Unlit Sprout', rarity: 'uncommon', habitatTags: ['lampwood'], baseHp: 32, baseAtk: 9, ac: 11 },
    { id: 'species_path_wisp', name: 'Path Wisp', rarity: 'rare', habitatTags: ['lampwood'], baseHp: 22, baseAtk: 16, ac: 13 },
    { id: 'species_hollow_keeper', name: 'Hollow Keeper', rarity: 'epic', habitatTags: ['lampwood'], baseHp: 180, baseAtk: 22, ac: 14 },
  ],
  items: [
    { id: 'item_oak_staff', name: 'Oak Staff', category: 'weapon', goldValue: 6, repairCostPerPoint: 0.5 },
    { id: 'item_lampwood_map', name: 'Lampwood Map', category: 'key', goldValue: 0, repairCostPerPoint: 0 },
    { id: 'item_spent_wick', name: 'Spent Wick', category: 'material', goldValue: 1, repairCostPerPoint: 0 },
    { id: 'item_fresh_wick', name: 'Fresh Wick', category: 'material', goldValue: 2, repairCostPerPoint: 0 },
    { id: 'item_path_glass', name: 'Path Glass', category: 'material', goldValue: 3, repairCostPerPoint: 0 },
    { id: 'item_keeper_lens', name: 'Keeper Lens', category: 'material', goldValue: 6, repairCostPerPoint: 0 },
  ],
  quests: [
    {
      id: 'quest_lanternfolk_race_1',
      title: 'Keep the Path Lit',
      family: 'race',
      hidden: false,
      unlocksQuestId: 'quest_lanternfolk_race_2',
      rewardGold: 100,
      rewardXp: 50,
      objectives: [
        { id: 'visit_path', kind: 'visit_place', placeId: 'poi_lampwood_path' },
        { id: 'kill_moths', kind: 'ledger_kill', speciesId: 'species_path_moth', count: 3 },
        { id: 'deliver_wick', kind: 'deliver_item', itemId: 'item_spent_wick', npcId: 'npc_pathwarden_sila' },
      ],
    },
    {
      id: 'quest_lanternfolk_race_2',
      title: 'The Unlit Bend',
      family: 'race',
      hidden: false,
      unlocksQuestId: 'quest_lanternfolk_race_3',
      rewardGold: 200,
      rewardXp: 100,
      objectives: [
        { id: 'visit_bend', kind: 'visit_place', placeId: 'poi_unlit_bend' },
        { id: 'kill_sprout', kind: 'ledger_kill', speciesId: 'species_unlit_sprout', count: 1 },
        { id: 'talk_sila', kind: 'talk_to_npc', npcId: 'npc_pathwarden_sila' },
      ],
    },
    {
      id: 'quest_lanternfolk_race_3',
      title: "Sila's Watch",
      family: 'race',
      hidden: true,
      unlocksQuestId: null,
      rewardGold: 500,
      rewardXp: 300,
      objectives: [
        { id: 'collect_glass', kind: 'collect_item', itemId: 'item_path_glass', count: 5 },
        { id: 'deliver_glass', kind: 'deliver_item', itemId: 'item_path_glass', npcId: 'npc_pathwarden_sila' },
      ],
    },
    {
      id: 'quest_wick_1',
      title: 'Apprentice Wick',
      family: 'profession',
      hidden: false,
      unlocksQuestId: 'quest_wick_2',
      rewardGold: 50,
      rewardXp: 20,
      objectives: [
        { id: 'collect_spent', kind: 'collect_item', itemId: 'item_spent_wick', count: 8 },
        { id: 'deliver_spent', kind: 'deliver_item', itemId: 'item_spent_wick', npcId: 'npc_wick_tender' },
      ],
    },
    {
      id: 'quest_wick_2',
      title: 'Journeyman Wick',
      family: 'profession',
      hidden: false,
      unlocksQuestId: 'quest_wick_3',
      rewardGold: 150,
      rewardXp: 60,
      objectives: [
        { id: 'visit_loft', kind: 'visit_place', placeId: 'poi_wickhaven_loft' },
        { id: 'kill_beetles', kind: 'ledger_kill', speciesId: 'species_wick_beetle', count: 5 },
        { id: 'collect_fresh', kind: 'collect_item', itemId: 'item_fresh_wick', count: 4 },
      ],
    },
    {
      id: 'quest_wick_3',
      title: 'Master Wick',
      family: 'profession',
      hidden: false,
      unlocksQuestId: null,
      rewardGold: 500,
      rewardXp: 120,
      objectives: [
        { id: 'collect_lens', kind: 'collect_item', itemId: 'item_keeper_lens', count: 1 },
        { id: 'deliver_lens', kind: 'deliver_item', itemId: 'item_keeper_lens', npcId: 'npc_wick_tender' },
      ],
    },
    {
      id: 'quest_lampwood_zone_1',
      title: 'Lamps Going Out',
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: 'quest_lampwood_zone_2',
      rewardGold: 75,
      rewardXp: 40,
      objectives: [
        { id: 'visit_ember', kind: 'visit_place', placeId: 'poi_ember_cut' },
        { id: 'talk_brann', kind: 'talk_to_npc', npcId: 'npc_guide_brann' },
      ],
    },
    {
      id: 'quest_lampwood_zone_2',
      title: 'Watch-Lantern Dark',
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: 'quest_lampwood_zone_3',
      rewardGold: 150,
      rewardXp: 100,
      objectives: [
        { id: 'visit_watch', kind: 'visit_place', placeId: 'poi_watch_lantern' },
        { id: 'kill_deer', kind: 'ledger_kill', speciesId: 'species_shade_deer', count: 3 },
      ],
    },
    {
      id: 'quest_lampwood_zone_3',
      title: 'The Hollow Mouth',
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: null,
      rewardGold: 300,
      rewardXp: 200,
      objectives: [
        { id: 'visit_mouth', kind: 'visit_place', placeId: 'poi_hollow_mouth' },
        { id: 'kill_keeper', kind: 'ledger_kill', speciesId: 'species_hollow_keeper', count: 1 },
        { id: 'talk_sila2', kind: 'talk_to_npc', npcId: 'npc_pathwarden_sila' },
      ],
    },
  ],
  dungeons: [
    {
      id: 'dungeon_unlit_hollow',
      name: 'Unlit Hollow',
      entrancePlaceId: 'poi_hollow_mouth',
      soloable: true,
      rooms: [
        { id: 'uh_mouth', name: 'Root Mouth', describeBeforeCreature: true, encounter: null, isBoss: false, isCheckpoint: true, exits: ['uh_path'] },
        {
          id: 'uh_path',
          name: 'Moth Gallery',
          describeBeforeCreature: true,
          encounter: [{ speciesId: 'species_path_moth', count: 3 }],
          isBoss: false,
          isCheckpoint: false,
          exits: ['uh_dark'],
        },
        {
          id: 'uh_dark',
          name: 'Unlit Gallery',
          describeBeforeCreature: true,
          encounter: [
            { speciesId: 'species_path_moth', count: 2 },
            { speciesId: 'species_unlit_sprout', count: 1, elite: true },
          ],
          isBoss: false,
          isCheckpoint: true,
          exits: ['uh_choice'],
        },
        { id: 'uh_choice', name: 'Two Wicks', describeBeforeCreature: true, encounter: null, isBoss: false, isCheckpoint: false, exits: ['uh_boss'] },
        {
          id: 'uh_boss',
          name: "Keeper's Dark",
          describeBeforeCreature: true,
          encounter: [{ speciesId: 'species_hollow_keeper', count: 1 }],
          isBoss: true,
          isCheckpoint: false,
          exits: [],
        },
      ],
    },
  ],
};
