import type { ZoneSlice } from '../../types';

export const REEDFEN: ZoneSlice = {
  places: [
    {
      id: 'poi_reedfen_square',
      name: 'Reedfen Square',
      zoneId: 'reedfen',
      mapScale: 'street',
      dangerTier: 'safe',
      outdoor: true,
      exits: ['poi_reedfen_marsh', 'poi_reedfen_hall', 'poi_reedfen_crossroads', 'poi_reedfen_pier', 'poi_millcross'],
      npcIds: ['npc_hearthborn_elder'],
    },
    {
      id: 'poi_millcross',
      name: 'Millcross',
      zoneId: 'reedfen',
      mapScale: 'street',
      dangerTier: 'safe',
      outdoor: true,
      exits: ['poi_reedfen_square'],
      npcIds: [],
    },
    {
      id: 'poi_reedfen_marsh',
      name: 'Reedfen Marsh',
      zoneId: 'reedfen',
      mapScale: 'street',
      dangerTier: 'low',
      outdoor: true,
      exits: ['poi_reedfen_square', 'poi_reedfen_marsh_edge', 'poi_lampwood_gate', 'poi_reedfen_mill'],
      npcIds: [],
    },
    {
      id: 'poi_reedfen_hall',
      name: 'Hearthborn Hall',
      zoneId: 'reedfen',
      mapScale: 'dungeon',
      dangerTier: 'safe',
      outdoor: false,
      exits: ['poi_reedfen_square'],
      npcIds: ['npc_hall_keeper'],
    },
    {
      id: 'poi_reedfen_pier',
      name: 'Reedfen Pier',
      zoneId: 'reedfen',
      mapScale: 'street',
      dangerTier: 'safe',
      outdoor: true,
      exits: ['poi_reedfen_square', 'poi_reedfen_crossroads'],
      npcIds: ['npc_pier_watcher', 'npc_lantern_keeper'],
    },
    {
      id: 'poi_reedfen_mill',
      name: 'Old Mill',
      zoneId: 'reedfen',
      mapScale: 'dungeon',
      dangerTier: 'safe',
      outdoor: false,
      exits: ['poi_reedfen_marsh'],
      npcIds: ['npc_miller'],
    },
    {
      id: 'poi_reedfen_crossroads',
      name: 'Reedfen Crossroads',
      zoneId: 'reedfen',
      mapScale: 'street',
      dangerTier: 'safe',
      outdoor: true,
      exits: ['poi_reedfen_square', 'poi_reedfen_pier'],
      npcIds: ['npc_crossroads_merchant'],
    },
    {
      id: 'poi_reedfen_marsh_edge',
      name: 'Marsh Edge',
      zoneId: 'reedfen',
      mapScale: 'street',
      dangerTier: 'low',
      outdoor: true,
      exits: ['poi_reedfen_marsh', 'poi_lampwood_gate'],
      npcIds: [],
    },
    {
      id: 'poi_lampwood_gate',
      name: 'Lampwood Gate',
      zoneId: 'reedfen',
      mapScale: 'street',
      dangerTier: 'medium',
      outdoor: true,
      exits: ['poi_reedfen_marsh_edge', 'poi_reedfen_marsh'],
      npcIds: [],
      dungeonId: 'dungeon_lampwood_gate',
    },
  ],
  npcs: [
    { id: 'npc_hearthborn_elder', name: 'Elder Mara', placeId: 'poi_reedfen_square', role: 'quest', durable: true },
    { id: 'npc_miller', name: 'Miller Tobin', placeId: 'poi_reedfen_mill', role: 'profession', durable: true },
    { id: 'npc_lantern_keeper', name: 'Keeper Wynn', placeId: 'poi_reedfen_pier', role: 'profession', durable: true },
    { id: 'npc_pier_watcher', name: 'Watcher Dell', placeId: 'poi_reedfen_pier', role: 'local', durable: true },
    { id: 'npc_hall_keeper', name: 'Keeper Renna', placeId: 'poi_reedfen_hall', role: 'hub', durable: true },
    { id: 'npc_crossroads_merchant', name: 'Merchant Fenn', placeId: 'poi_reedfen_crossroads', role: 'merchant', durable: true },
  ],
  species: [
    { id: 'species_reedfen_hatchling', name: 'Reedfen Hatchling', rarity: 'common', habitatTags: ['reedfen', 'marsh'], baseHp: 20, baseAtk: 5, ac: 10 },
    { id: 'species_mill_rat', name: 'Mill Rat', rarity: 'common', habitatTags: ['reedfen', 'mill'], baseHp: 12, baseAtk: 3, ac: 9 },
    { id: 'species_marsh_gnat', name: 'Marsh Gnat', rarity: 'common', habitatTags: ['reedfen', 'marsh'], baseHp: 6, baseAtk: 2, ac: 12 },
    { id: 'species_reed_frog', name: 'Reed Frog', rarity: 'common', habitatTags: ['reedfen', 'marsh'], baseHp: 10, baseAtk: 3, ac: 10 },
    { id: 'species_marsh_lurker', name: 'Marsh Lurker', rarity: 'uncommon', habitatTags: ['reedfen', 'marsh'], baseHp: 45, baseAtk: 12, ac: 12 },
    { id: 'species_lampwood_sprout', name: 'Lampwood Sprout', rarity: 'uncommon', habitatTags: ['reedfen', 'lampwood'], baseHp: 30, baseAtk: 8, ac: 11 },
    { id: 'species_pier_crab', name: 'Pier Crab', rarity: 'uncommon', habitatTags: ['reedfen', 'pier'], baseHp: 35, baseAtk: 7, ac: 13 },
    { id: 'species_crossroads_wolf', name: 'Crossroads Wolf', rarity: 'uncommon', habitatTags: ['reedfen'], baseHp: 40, baseAtk: 10, ac: 12 },
    { id: 'species_heartstone_golem', name: 'Heartstone Golem', rarity: 'rare', habitatTags: ['reedfen'], baseHp: 80, baseAtk: 15, ac: 14 },
    { id: 'species_marsh_wisp', name: 'Marsh Wisp', rarity: 'rare', habitatTags: ['reedfen', 'marsh'], baseHp: 25, baseAtk: 18, ac: 13 },
    { id: 'species_old_mill_spectre', name: 'Old Mill Spectre', rarity: 'rare', habitatTags: ['reedfen', 'mill'], baseHp: 50, baseAtk: 14, ac: 12 },
    { id: 'species_lampwood_warden', name: 'Lampwood Warden', rarity: 'epic', habitatTags: ['reedfen', 'lampwood'], baseHp: 200, baseAtk: 25, ac: 14 },
    { id: 'species_reedfen_salamander', name: 'Reedfen Salamander', rarity: 'uncommon', habitatTags: ['reedfen', 'marsh'], baseHp: 35, baseAtk: 11, ac: 11 },
    { id: 'species_mire_viper', name: 'Mire Viper', rarity: 'uncommon', habitatTags: ['reedfen', 'marsh'], baseHp: 28, baseAtk: 14, ac: 12 },
    { id: 'species_lamp_moth', name: 'Lamp Moth', rarity: 'common', habitatTags: ['reedfen', 'lampwood'], baseHp: 8, baseAtk: 4, ac: 11 },
    { id: 'species_brine_crawler', name: 'Brine Crawler', rarity: 'uncommon', habitatTags: ['reedfen', 'pier'], baseHp: 38, baseAtk: 9, ac: 12 },
  ],
  items: [
    { id: 'item_hearthborn_knife', name: 'Hearthborn Cutting Knife', category: 'weapon', goldValue: 5, repairCostPerPoint: 0.5 },
    { id: 'item_reedfen_map', name: 'Reedfen Map', category: 'key', goldValue: 0, repairCostPerPoint: 0 },
    { id: 'item_heartstone_shard', name: 'Heartstone Shard', category: 'material', goldValue: 2, repairCostPerPoint: 0 },
    { id: 'item_reedfen_scale', name: 'Reedfen Scale', category: 'material', goldValue: 2, repairCostPerPoint: 0 },
    { id: 'item_marsh_grain', name: 'Marsh Grain', category: 'material', goldValue: 1, repairCostPerPoint: 0 },
    { id: 'item_millstone_fragment', name: 'Millstone Fragment', category: 'material', goldValue: 3, repairCostPerPoint: 0 },
    { id: 'item_polished_grain', name: 'Polished Grain', category: 'material', goldValue: 2, repairCostPerPoint: 0 },
    { id: 'item_millstone_core', name: 'Millstone Core', category: 'material', goldValue: 8, repairCostPerPoint: 0 },
    { id: 'item_lurker_eye', name: 'Lurker Eye', category: 'material', goldValue: 4, repairCostPerPoint: 0 },
  ],
  quests: [
    {
      id: 'quest_hearthborn_race_1',
      title: "The Hearthborn's Request",
      family: 'race',
      hidden: false,
      unlocksQuestId: 'quest_hearthborn_race_2',
      rewardGold: 100,
      rewardXp: 50,
      objectives: [
        { id: 'visit_marsh', kind: 'visit_place', placeId: 'poi_reedfen_marsh' },
        { id: 'kill_hatch', kind: 'ledger_kill', speciesId: 'species_reedfen_hatchling', count: 3 },
        { id: 'deliver_scale', kind: 'deliver_item', itemId: 'item_reedfen_scale', npcId: 'npc_hearthborn_elder' },
      ],
    },
    {
      id: 'quest_hearthborn_race_2',
      title: 'Warmth in the Marsh',
      family: 'race',
      hidden: false,
      unlocksQuestId: 'quest_hearthborn_race_3',
      rewardGold: 200,
      rewardXp: 100,
      objectives: [
        { id: 'visit_edge', kind: 'visit_place', placeId: 'poi_reedfen_marsh_edge' },
        { id: 'kill_lurker', kind: 'ledger_kill', speciesId: 'species_marsh_lurker', count: 1 },
        { id: 'talk_mara', kind: 'talk_to_npc', npcId: 'npc_hearthborn_elder' },
      ],
    },
    {
      id: 'quest_hearthborn_race_3',
      title: "The Elder's Trust",
      family: 'race',
      hidden: true,
      unlocksQuestId: null,
      rewardGold: 500,
      rewardXp: 300,
      objectives: [
        { id: 'collect_shards', kind: 'collect_item', itemId: 'item_heartstone_shard', count: 5 },
        { id: 'deliver_shards', kind: 'deliver_item', itemId: 'item_heartstone_shard', npcId: 'npc_hearthborn_elder' },
      ],
    },
    {
      id: 'quest_miller_1',
      title: 'Apprentice Miller',
      family: 'profession',
      hidden: false,
      unlocksQuestId: 'quest_miller_2',
      rewardGold: 50,
      rewardXp: 20,
      objectives: [
        { id: 'collect_grain', kind: 'collect_item', itemId: 'item_marsh_grain', count: 10 },
        { id: 'deliver_grain', kind: 'deliver_item', itemId: 'item_marsh_grain', npcId: 'npc_miller' },
      ],
    },
    {
      id: 'quest_miller_2',
      title: 'Journeyman Miller',
      family: 'profession',
      hidden: false,
      unlocksQuestId: 'quest_miller_3',
      rewardGold: 150,
      rewardXp: 60,
      objectives: [
        { id: 'visit_mill', kind: 'visit_place', placeId: 'poi_reedfen_mill' },
        { id: 'kill_rats', kind: 'ledger_kill', speciesId: 'species_mill_rat', count: 5 },
        { id: 'collect_frag', kind: 'collect_item', itemId: 'item_millstone_fragment', count: 1 },
      ],
    },
    {
      id: 'quest_miller_3',
      title: 'Master Miller',
      family: 'profession',
      hidden: false,
      unlocksQuestId: null,
      rewardGold: 500,
      rewardXp: 120,
      objectives: [
        { id: 'collect_polished', kind: 'collect_item', itemId: 'item_polished_grain', count: 10 },
        { id: 'collect_core', kind: 'collect_item', itemId: 'item_millstone_core', count: 1 },
        { id: 'deliver_core', kind: 'deliver_item', itemId: 'item_millstone_core', npcId: 'npc_miller' },
      ],
    },
    {
      id: 'quest_reedfen_zone_1',
      title: 'Trouble at the Pier',
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: 'quest_reedfen_zone_2',
      rewardGold: 75,
      rewardXp: 40,
      objectives: [
        { id: 'visit_pier', kind: 'visit_place', placeId: 'poi_reedfen_pier' },
        { id: 'talk_dell', kind: 'talk_to_npc', npcId: 'npc_pier_watcher' },
      ],
    },
    {
      id: 'quest_reedfen_zone_2',
      title: "The Lurker's Trail",
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: 'quest_reedfen_zone_3',
      rewardGold: 150,
      rewardXp: 100,
      objectives: [
        { id: 'visit_edge2', kind: 'visit_place', placeId: 'poi_reedfen_marsh_edge' },
        { id: 'kill_lurkers', kind: 'ledger_kill', speciesId: 'species_marsh_lurker', count: 3 },
        { id: 'collect_eye', kind: 'collect_item', itemId: 'item_lurker_eye', count: 1 },
      ],
    },
    {
      id: 'quest_reedfen_zone_3',
      title: 'Clearing the Reedfen',
      family: 'zone_story',
      hidden: false,
      unlocksQuestId: null,
      rewardGold: 300,
      rewardXp: 200,
      objectives: [
        { id: 'visit_gate', kind: 'visit_place', placeId: 'poi_lampwood_gate' },
        { id: 'kill_warden', kind: 'ledger_kill', speciesId: 'species_lampwood_warden', count: 1 },
        { id: 'talk_mara2', kind: 'talk_to_npc', npcId: 'npc_hearthborn_elder' },
      ],
    },
  ],
  dungeons: [
    {
      id: 'dungeon_lampwood_gate',
      name: 'Lampwood Gate',
      entrancePlaceId: 'poi_lampwood_gate',
      soloable: true,
      rooms: [
        { id: 'lg_entrance', name: 'Gate Arch', describeBeforeCreature: true, encounter: null, isBoss: false, isCheckpoint: true, exits: ['lg_corridor'] },
        {
          id: 'lg_corridor',
          name: 'Marsh Corridor',
          describeBeforeCreature: true,
          encounter: [{ speciesId: 'species_reedfen_hatchling', count: 3 }],
          isBoss: false,
          isCheckpoint: false,
          exits: ['lg_flood'],
        },
        {
          id: 'lg_flood',
          name: 'Flooded Chamber',
          describeBeforeCreature: true,
          encounter: [
            { speciesId: 'species_reedfen_hatchling', count: 2 },
            { speciesId: 'species_marsh_lurker', count: 1, elite: true },
          ],
          isBoss: false,
          isCheckpoint: true,
          exits: ['lg_lantern'],
        },
        { id: 'lg_lantern', name: 'The Lantern Room', describeBeforeCreature: true, encounter: null, isBoss: false, isCheckpoint: false, exits: ['lg_warden'] },
        {
          id: 'lg_warden',
          name: "Warden's Chamber",
          describeBeforeCreature: true,
          encounter: [{ speciesId: 'species_lampwood_warden', count: 1 }],
          isBoss: true,
          isCheckpoint: false,
          exits: [],
        },
      ],
    },
  ],
};
