#!/usr/bin/env python3
"""Generates original, quarantine-safe support data for SynapticGM and WOF."""
import json
from pathlib import Path
root=Path('/home/ubuntu/wof_support_data'); root.mkdir(exist_ok=True)

def entries(prefix, vals): return [{'id':f'{prefix}.{i+1:02d}','text':v} for i,v in enumerate(vals)]
# Each deck is intentionally short, original, and remix-ready.
decks={
'premises':['A gate census discovers one resident is counted twice.','A river loses its reflection before a trade summit.','A town inherits a clock that charges favors instead of hours.','A silent library lends memories written on seed paper.','A hill road rearranges itself after every honest confession.','A harvest bell rings for a field no map contains.','A treaty ship arrives with a crew from tomorrow.','A village wakes to find its wells full of warm starlight.','A ruined relay tower begins answering questions in bird calls.','A court hires strangers to identify a counterfeit season.','A forest keeps returning lost tools with new instructions.','A mountain stair opens only for people carrying unfinished work.','A market sells weather in sealed jars.','A lighthouse casts its beam inland for seven nights.','A caravan route has acquired a second sunset.','A palace archive has begun filing living people as artifacts.','A plague of polite doors appears in every empty wall.','A city votes to outlaw a song no one remembers hearing.','A buried engine grants one useful miracle per district.','A salt marsh produces footprints that predict negotiations.','A comet drops a map made of changing moss.','A museum’s exhibits ask to be returned to their owners.','A bridge accepts tolls only in promises.','An orchard grows keys instead of fruit.','A reservoir drains into an undiscovered valley.','A guild map shows a road that avoids every decision.','A winter festival receives letters from its future guests.','A broken statue appoints unwilling witnesses.','A train of lanterns crosses a road with no tracks.','A shrine’s caretaker vanishes leaving the job to the next visitor.','A coast town trades names to calm storms.','A city’s shadows begin arriving early.','A frontier post receives a census from an absent empire.','A harbor bell names one hidden debt each dawn.','A valley’s animals carry tiny stamped passports.','A public garden blooms only around unresolved arguments.','A new moon exposes a second set of town walls.','A ruined theater stages events before they happen.','A marketplace loses the ability to recognize ownership.','A watchtower reports a threat that is slowly becoming true.'],
'hardLaws':['No person may cross a marked threshold twice in one day.','Fire reveals only what its keeper has already witnessed.','Names spoken in debt become binding until repaid.','Water remembers every vessel that carried it.','Doors open only after a truthful offer.','A promise may be traded but never erased.','Every bridge keeps a ledger of crossings.','Stone records weight, not words.','Light cannot enter a room that has not been invited.','Maps redraw themselves after an honest journey.','The dead leave receipts, not ghosts.','Time passes unevenly only where clocks are broken.','No blade can cut a route that has been named.','Food shared under rain creates a temporary truce.','A lie cannot be written in blue ink.','Storms follow unpaid favors.','A city wall recognizes its current defenders.','Every oath has a visible witness-mark.','Seeds remember the last hand that planted them.','A locked box may answer one question before opening.','Metal cools only after its owner forgives a debt.','A road forgets travelers who refuse to look back.','Dreams can be taxed but not sold.','A bell can summon only those who heard its first note.','Mirrors show obligations before faces.','No creature may claim land without maintaining it.','Written orders expire at the next sunrise.','A river cannot carry a secret upstream.','All bargains require an offered alternative.','A wound heals slowly when its cause remains unspoken.','A crown weighs more for each ignored petition.','Wind carries messages only to named landmarks.','A lantern cannot be lit by stolen fuel.','A map may omit danger but cannot invent safety.','Every gate remembers its last refusal.','Snow preserves tracks until a choice is made.','Coins retain the mood of their final exchange.','A chorus can open one sealed archive each year.','The oldest tree knows routes but not motives.','Every rescue creates a future obligation.'],
'places':['A rain-scarred toll bridge','A stepped quarry market','A reed-walled ferry stop','A clockwork herb garden','A lantern repair lane','A salt cellar archive','A wind-carved shrine','A half-flooded courthouse','A rooftop seed exchange','A basalt stairwell','A silent bell orchard','A fogbound customs gate','A copper bathhouse','A hilltop observatory','A moss-roofed hostel','A river-lock workshop','A crumbling theatre vault','A clay kiln district','A stilted fish market','A skybridge granary','A hidden cistern library','A thorn hedgerow maze','A sealed survey camp','A candlelit debt office','A black-glass beach','A sunken caravan yard','A weather-vane cemetery','A spice warehouse with false walls','A cliffside courier post','A root-cellar chapel','A winter greenhouse','A mirror-polished alley','A rope-lift station','A forgotten signal tower','A public oath wall','A pebble-sorting monastery','A canal-side forge','A drifting market barge','A quiet embassy garden','A wildflower checkpoint'],
'npcs':['A route clerk hiding a forged itinerary','A patient locksmith collecting impossible keys','A tired ranger protecting an unmarked grave','A cheerful broker with one missing creditor','A scholar whose notes alter after midnight','A baker who can smell old bargains','A courier with a rival route map','A retired guard training unpaid volunteers','A ferry captain who refuses one shoreline','A child inventor seeking a lost blueprint','A magistrate afraid of a correct verdict','A gardener growing evidence in coded rows','A musician who trades melodies for rumors','A miner who found a door beneath the seam','A healer who owes service to a storm','A cartographer whose compass points to regret','A shopkeeper protecting a false identity','A diplomat with a failing truce schedule','A mason repairing damage nobody remembers causing','A cook who serves one meal from the future','A watch officer tracking a polite saboteur','A historian hiding a living artifact','A scout whose reports arrive out of order','A debt collector trying to break their own contract','A mechanic whose machines dream of the road','A fisher who knows the tide’s secret calendar','A lantern tender missing their apprentice','A young rival obsessed with fair competition','A judge who hears testimony from objects','A trader trapped by an inherited vow','A seamstress stitching maps into coats','A botanist whose samples whisper directions','A courier guild elder facing a mutiny','A prisoner offered a role in the city archive','A pilgrim carrying a counterfeit relic','A harbor pilot charting a vanished reef','A village teacher defending forbidden questions','A craftsperson building a bridge for one person','A quiet orphan with a faction seal','A clockkeeper who has stopped sleeping'],
'quests':['Find who altered a public route ledger.','Escort a disputed supply crate through a closed district.','Decide whether to reveal a harmful true map.','Recover a promise before it is sold.','Trace a rumor back to its first witness.','Repair a gate without restoring its old injustice.','Choose the keeper of a dangerous key orchard.','Stop a faction clock without rewarding its cruelty.','Prove whether a missing NPC left voluntarily.','Negotiate a rescue that creates a new debt.','Clear a dungeon room without resetting its history.','Expose a forged weather permit.','Find a safe path for a displaced household.','Recover a tool that remembers its owner.','Decide which of two true stories enters the archive.','Break a supply monopoly without collapsing the market.','Follow a rival’s fair but dangerous challenge.','Return a creature to a habitat that has changed.','Resolve a border dispute using observed evidence.','Test a custom law against an unintended consequence.','Protect a festival from a nonviolent sabotage.','Choose whether to spend a favor or preserve it.','Locate an interior hidden by map error.','Rebuild a bridge while storms advance.','Find the source of a false quest notice.','Investigate a clock that is charging the wrong person.','Recover a lost party member’s route memory.','Help a faction admit a public mistake.','Decide how a successor inherits a role.','Stop a dungeon restock from consuming a village resource.','Prove a market shortage is manufactured.','Secure a lantern road before nightfall.','Resolve a rumor without naming an innocent person.','Recover a legal title from a flooded archive.','Choose a witness for an irreversible oath.','Find why a known route became impossible.','Prevent an NPC’s plan without reading their mind.','Return a stolen map without granting amnesty.','Defend a low-stakes home from a high-stakes clock.','Decide whether an old legend deserves correction.'],
'openingStakes':['A trusted NPC needs an answer before dusk.','Your starting kit contains an item claimed by another person.','The road behind you closes at sundown.','A public notice names you as a witness.','A local faction offers safety at a visible cost.','Your first map pin is only a rumor.','A harmless task reveals a missing resource.','A rival arrives with a fair challenge.','A weather shift threatens the starting place.','A hidden clock is about to become visible.','A companion asks you to keep a difficult promise.','A gate requires a choice, not a key.','Your first reward will overfill your pack.','A route is safe only if you leave something behind.','An injured stranger knows a useful but partial truth.','A public celebration masks a private deadline.','A local law conflicts with your immediate goal.','Your first check can protect a person or a resource.','A familiar place has changed since morning.','A message arrives with proof but no sender.'],
'kits':['Rainproof courier satchel','Stoneworker hand kit','Lantern tender roll','Field apothecary wrap','Surveyor’s cord and chalk','Canal mechanic pouch','Archivist’s safe notebook','Hearth guard bundle','Reedfen trail pack','Trade clerk ledger case','Quiet investigator wallet','Cliff runner harness','Garden keeper tools','Ferry hand kit','Signal repair pouch','Oath witness case','Weather watcher cloak','Ranger’s repair roll','Mapmaker tube','Market porter sling'],
'folkWorldShapes':['Hearthborn orchard communes','Lanternfolk road caravans','Saltkin tide towns','Stonevein stair holds','Reedfen floating villages','Lampwood canopy hamlets','Ash Compact city wards','Tide Covenant harbor leagues','Cloudstep plateaus','Mossbound canal cities','Glassshore reef enclaves','Cinderfield kiln marches','Rivergate bridge republics','Winterwell reservoir towns','Sunvault terrace states','Hollowroad tunnel villages','Thornwatch hedge borders','Copperwake repair fleets','Dawnbarrow hill councils','Mistlock archive islands']}
(root/'synapticgm_randomize_decks.json').write_text(json.dumps({k:entries(k,v) for k,v in decks.items()},indent=2))

variants=[
 ('ash-tide-compact','The Ash-Tide Compact','Classic faction fantasy','Ash Compact and Tide Covenant contest a failing treaty road.'),
 ('understep-delves','Understep Delves','Dungeon-delver deep dark','Expeditions descend changing strata and must return with the truth intact.'),
 ('brinewatch-ledgers','Brinewatch Ledgers','Coastal salt-trade intrigue','Harbor families, salt routes and storm debts reshape a coastal city.'),
 ('granite-stair-holds','Granite Stair Holds','Stone-and-stair mountain holds','High holds endure avalanche politics and the cost of deep extraction.'),
 ('lantern-road','Lantern Road Pilgrimage','Lanternfolk night-road','Light is a shared route resource across a nightward pilgrimage.'),
 ('hearthward','Hearthward','Hearthborn settlement-builder light','A small settlement defends its home while remaining adventure-first.'),
 ('collectors-compact','Collector’s Compact','Hybrid collector faction war','Creature accords and faction pressure collide across the borderlands.')]
all_types=['Ember','Tide','Gale','Root','Stone','Veil','Spark','Gloom','Gleam','Bloom']
wof={}
for vi,(vid,title,mode,pitch) in enumerate(variants):
    enemies=[{'id':f'{vid}.signature.{i+1:02d}','name':f'{all_types[(i+vi)%10]} {['Warden','Rover','Mason','Whisper','Runner','Keeper'][i%6]} {i+1}','role':['scout','guard','brute','mystic','leader'][i%5],'tier':1+i%5} for i in range(30)]
    materials=[{'id':f'{vid}.material.{i+1:02d}','name':f'{all_types[(i+vi)%10].lower()}-{['fiber','ore','resin','salt','glass'][i%5]}','use':['repair','craft','trade','quest'][i%4]} for i in range(20)]
    quests=[f'{title}: resolve {decks["quests"][(i+vi*3)%40].lower()}' for i in range(15)]
    dungeons=[f'{title}: expedition into the {['sealed stair','flooded vault','wind quarry','lantern trench','ash orchard'][i%5]} to {['recover evidence','secure a route','stop a clock','map a return','rescue a team'][i%5]}.' for i in range(10)]
    clocks=[{'id':f'{vid}.clock.{i+1}','stageNames':['rumor','pressure','turning','aftermath'],'trigger':f'{all_types[(i+vi)%10]} resource falls below threshold or player-visible deadline expires','interrupt':'investigate, negotiate, reroute, or spend a declared resource'} for i in range(3)]
    wof[vid]={'title':title,'mode':mode,'pitch':pitch,'signatureEnemies':enemies,'materials':materials,'questSeeds':quests,'expeditionSeeds':dungeons,'factionClocks':clocks}
(root/'wof_other_variants_content.json').write_text(json.dumps(wof,indent=2))
print('Generated decks plus seven WOF variant content tables')
