#!/usr/bin/env python3
import csv
from pathlib import Path

ROOT=Path('/home/ubuntu/SynapticGM_story_tones_gm_personality_2026-08-26')
OUT=ROOT/'deliverables'
PREFIX='SynapticGM_story_tones_gm_personality_2026-08-26_'
NEG='no readable text; no letters or numbers; no dialogue balloons; no captions; no SFX glyphs; no logos; no watermarks; no UI; no HUD; no living-artist or studio imitation; no franchise lookalikes; no copyrighted character likeness; no extra factual entities not supplied by SceneManifest'

rows=[
{
'tone_id':'grimdark_bleak_consequence','primary_kit_key':'infernal-pact','secondary_kit_keys':'bone-reliquary|undead-ossuary','false_friend_kits_to_avoid':'ember-depths|vampire-nocturne','font_dice_notes':'Use severe high-contrast title tokens and dark neutral body tokens; exact premium font/dice mapping INPUT REQUIRED. Infernal means sulfur, brass, seals, and contract heat—not magma.','kid_ok':'conditional','recipe_id':'recipe_grimdark_bleak_consequence_v1','plate_delta':'light_event=low raking sulfur glow through smoke; palette_pair=charcoal+brass-yellow; composition_bias=small figure against damaged civic scale; protect readable silhouette; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Select ruins, confrontation, or aftermath layouts only after Template 01–20 definitions are supplied.','camera_family':'low_three_quarter|compressed_long_lens','gutter_token':'charcoal_hairline','role_preference':'atmosphere_bg>frame_ornament>panel_tile','negative_prompt':NEG,'kid_visual_rewrite':'Replace gore, corpses, impalement, and despair poses with damaged gear, smoke, blocked routes, and determined recovery; keep consequence visible but non-graphic.'},
{
'tone_id':'cozy_low_stakes_comfort','primary_kit_key':'wood-elf-grove','secondary_kit_keys':'high-elf-spire|parchment-ledger','false_friend_kits_to_avoid':'undead-ossuary|infernal-pact|noir-crimson','font_dice_notes':'Prefer highly legible warm serif body text and soft natural dice; pack-specific token names INPUT REQUIRED.','kid_ok':'yes','recipe_id':'recipe_cozy_low_stakes_comfort_v1','plate_delta':'light_event=dappled window or canopy light; palette_pair=moss-green+honey; composition_bias=eye-level shared activity with generous breathing room; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose quiet-arrival, shared-task, or object-discovery layouts after template definitions are supplied.','camera_family':'eye_level_medium|gentle_overhead','gutter_token':'cream_soft','role_preference':'panel_tile>atmosphere_bg>frame_ornament','negative_prompt':NEG,'kid_visual_rewrite':'Keep warm light, clear faces, open paths, and friendly distance; remove sharp weapons, looming silhouettes, and ambiguous menace.'},
{
'tone_id':'cozy_brutal','primary_kit_key':'orc-warcamp','secondary_kit_keys':'goblin-scrapheap|ember-depths','false_friend_kits_to_avoid':'infernal-pact|vampire-nocturne','font_dice_notes':'Pair sturdy utilitarian body type with warm camp accents; exact dice set INPUT REQUIRED. Ember means forge or magma heat, not occult pact sulfur.','kid_ok':'conditional','recipe_id':'recipe_cozy_brutal_v1','plate_delta':'light_event=campfire edge against hard impact sparks; palette_pair=soot-black+stew-amber; composition_bias=close action foreground with safe communal anchor behind; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Select duel, aftermath, or shared-meal layouts only after the template guide is present.','camera_family':'handheld_medium|impact_closeup','gutter_token':'ink_heavy','role_preference':'frame_ornament>atmosphere_bg>panel_tile','negative_prompt':NEG,'kid_visual_rewrite':'Convert wounds to scuffs, torn cloth, dust, and comic soot; keep the camp, meal, teamwork, and honest loss of position or item.'},
{
'tone_id':'pulp_kinetic_adventure','primary_kit_key':'dragon-hoard','secondary_kit_keys':'phoenix-ashrise|orc-warcamp','false_friend_kits_to_avoid':'parchment-ledger|bone-reliquary','font_dice_notes':'Use bold condensed title tokens only for HTML/SVG overlay and high-contrast dice; exact premium mapping INPUT REQUIRED.','kid_ok':'yes','recipe_id':'recipe_pulp_kinetic_adventure_v1','plate_delta':'light_event=hard backlight plus sparks; palette_pair=vermillion+sunlit-gold; composition_bias=diagonal motion with one readable hazard and one escape vector; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Prioritize chase, leap, reveal, and narrow-escape layouts after template definitions are supplied.','camera_family':'wide_action|low_angle_tracking','gutter_token':'white_slash','role_preference':'atmosphere_bg>panel_tile>frame_ornament','negative_prompt':NEG,'kid_visual_rewrite':'Keep speed, discovery, and near-misses; show theatrical defeat rather than injury and leave exits visually open.'},
{
'tone_id':'gothic_moonlit_dread','primary_kit_key':'vampire-nocturne','secondary_kit_keys':'dark-elf-umbrance|glass-spire','false_friend_kits_to_avoid':'infernal-pact|undead-ossuary|noir-crimson','font_dice_notes':'PROVIDED SUMMARY: flock velvet, moonlit edge, Wine Obsidian dice, and Grenze for titles only. Body text must remain a readable non-display face.','kid_ok':'conditional','recipe_id':'recipe_gothic_moonlit_dread_v1','plate_delta':'light_event=single cold moon edge through interior shadow; palette_pair=wine-black+silver-blue; composition_bias=deep doorway or window frame with negative space and no confirmed hidden figure; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose threshold, portrait-distance, or architectural-dread layouts only after definitions are supplied.','camera_family':'locked_symmetry|slow_push_composition','gutter_token':'wine_velvet','role_preference':'frame_ornament>atmosphere_bg>panel_tile','negative_prompt':NEG,'kid_visual_rewrite':'Shift terror to theatrical mystery: moonlight, curtains, cobwebs, and curious shadows; remove blood, predatory intimacy, corpses, and trapped-child imagery.'},
{
'tone_id':'litrpg_system_registrar','primary_kit_key':'phosphor-terminal','secondary_kit_keys':'neon-protocol|cyborg-chassis','false_friend_kits_to_avoid':'glass-spire|angelic-radiance','font_dice_notes':'Monospaced metrics in HTML/SVG only, with accessible body fallback; dice may use luminous edge but never unreadable numerals. Exact premium tokens INPUT REQUIRED.','kid_ok':'yes','recipe_id':'recipe_litrpg_system_registrar_v1','plate_delta':'light_event=phosphor glow on physical surfaces; palette_pair=near-black+phosphor-green; composition_bias=centered subject with empty overlay-safe margins, but pixels contain no interface; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Select scan, threshold, or inventory-object layouts after template definitions are supplied.','camera_family':'orthographic_medium|centered_scan','gutter_token':'phosphor_hairline','role_preference':'panel_tile>frame_ornament>atmosphere_bg','negative_prompt':NEG,'kid_visual_rewrite':'Keep simple glowing shapes and friendly scale; remove surveillance threat, body horror, and dense pseudo-data.'},
{
'tone_id':'military_procedural','primary_kit_key':'dwarf-forgehall','secondary_kit_keys':'orc-warcamp|cyborg-chassis','false_friend_kits_to_avoid':'fae-glamour|angelic-radiance','font_dice_notes':'Use compact utilitarian labels and high-contrast dice; no stencil text inside imagery. Exact pack choices INPUT REQUIRED.','kid_ok':'conditional','recipe_id':'recipe_military_procedural_v1','plate_delta':'light_event=worklight pools with clear sightlines; palette_pair=gunmetal+signal-amber; composition_bias=wide spatial read showing only supplied cover, exits, and present units; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose briefing, objective, or formation layouts after template definitions are supplied.','camera_family':'high_oblique|shoulder_recon','gutter_token':'grid_hairline','role_preference':'atmosphere_bg>panel_tile>frame_ornament','negative_prompt':NEG,'kid_visual_rewrite':'Reframe combat as rescue, scouting, or team mission; replace firearms and wounds with tools, signals, shields, and clear safe routes.'},
{
'tone_id':'dry_wit_deadpan','primary_kit_key':'goblin-scrapheap','secondary_kit_keys':'parchment-ledger|noir-crimson','false_friend_kits_to_avoid':'fae-glamour|angelic-radiance','font_dice_notes':'Neutral readable type with one restrained accent; dice remain conventional. Exact premium mappings INPUT REQUIRED.','kid_ok':'yes','recipe_id':'recipe_dry_wit_deadpan_v1','plate_delta':'light_event=flat practical light interrupted by one absurdly precise highlight; palette_pair=dust-grey+acid-lime; composition_bias=static framing around an incongruous but supplied prop; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose reaction, object, or aftermath layouts only after definitions are supplied.','camera_family':'locked_medium|dead_center_wide','gutter_token':'neutral_thin','role_preference':'panel_tile>frame_ornament>atmosphere_bg','negative_prompt':NEG,'kid_visual_rewrite':'Use harmless visual mismatch and silly scale, never a child or player as the joke; keep hazards readable.'},
{
'tone_id':'warm_chronicle','primary_kit_key':'parchment-ledger','secondary_kit_keys':'wood-elf-grove|high-elf-spire','false_friend_kits_to_avoid':'phosphor-terminal|noir-crimson','font_dice_notes':'Warm bookish body face with modest illuminated initial treatment in HTML/SVG; tactile neutral dice. Exact pack tokens INPUT REQUIRED.','kid_ok':'yes','recipe_id':'recipe_warm_chronicle_v1','plate_delta':'light_event=late-afternoon window or hearth rim; palette_pair=parchment-cream+chestnut; composition_bias=human-scale tableau with one memory-bearing supplied prop; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose reunion, travel-rest, keepsake, or shared-table layouts after definitions are supplied.','camera_family':'eye_level_tableau|gentle_wide','gutter_token':'parchment_rule','role_preference':'frame_ornament>panel_tile>atmosphere_bg','negative_prompt':NEG,'kid_visual_rewrite':'Increase clarity and companionship; remove grief-heavy symbols unless explicitly present and keep the route forward visible.'},
{
'tone_id':'clinical_auditor','primary_kit_key':'glass-spire','secondary_kit_keys':'cyborg-chassis|phosphor-terminal','false_friend_kits_to_avoid':'angelic-radiance|fae-glamour','font_dice_notes':'Use neutral sans and tabular numerals in overlay; transparent or clear dice with high-contrast pips. Exact premium mapping INPUT REQUIRED.','kid_ok':'conditional','recipe_id':'recipe_clinical_auditor_v1','plate_delta':'light_event=cool diffuse inspection light; palette_pair=frosted-glass+graphite; composition_bias=orthogonal evidence layout with scale cues only when supplied; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose evidence, specimen, or site-survey layouts after definitions are supplied.','camera_family':'orthographic_close|top_down_evidence','gutter_token':'glass_rule','role_preference':'panel_tile>atmosphere_bg>frame_ornament','negative_prompt':NEG,'kid_visual_rewrite':'Turn forensic imagery into safe inspection and puzzle-solving; remove medical detail, body damage, and intimidating surveillance.'},
{
'tone_id':'mythic_portent','primary_kit_key':'angelic-radiance','secondary_kit_keys':'dragon-hoard|phoenix-ashrise','false_friend_kits_to_avoid':'neon-protocol|noir-crimson','font_dice_notes':'Use ceremonial display type only for overlay headings and accessible body text; luminous dice without sacred-symbol appropriation. Exact tokens INPUT REQUIRED.','kid_ok':'yes','recipe_id':'recipe_mythic_portent_v1','plate_delta':'light_event=column of dawn or eclipse rim; palette_pair=deep-indigo+old-gold; composition_bias=low-angle monumental silhouette with no invented deity or omen-object; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose arrival, vow, relic, or horizon-reveal layouts only after definitions are supplied.','camera_family':'low_angle_wide|frontal_iconic','gutter_token':'gold_rule','role_preference':'frame_ornament>atmosphere_bg>panel_tile','negative_prompt':NEG,'kid_visual_rewrite':'Make scale wondrous rather than apocalyptic; replace judgment, sacrifice, and doom symbols with stars, dawn, and protective geometry.'},
{
'tone_id':'street_balladeer','primary_kit_key':'neon-protocol','secondary_kit_keys':'goblin-scrapheap|noir-crimson','false_friend_kits_to_avoid':'high-elf-spire|angelic-radiance','font_dice_notes':'Use energetic display accents only in overlay, paired with plain body text; dice may be scuffed and high-contrast. Exact pack mapping INPUT REQUIRED.','kid_ok':'yes','recipe_id':'recipe_street_balladeer_v1','plate_delta':'light_event=streetlamp or sign spill without readable signage; palette_pair=electric-cyan+brick-red; composition_bias=street-level diagonal with audience-space and one supplied focal act; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose crowd-edge, performance, chase, or proclamation layouts after definitions are supplied.','camera_family':'street_level_wide|moving_medium','gutter_token':'torn_poster_edge','role_preference':'atmosphere_bg>frame_ornament>panel_tile','negative_prompt':NEG,'kid_visual_rewrite':'Keep music, movement, and friendly crowds; remove adult nightlife cues, threatening gangs, and humiliating caricature.'},
{
'tone_id':'ashen_archivist','primary_kit_key':'undead-ossuary','secondary_kit_keys':'bone-reliquary|parchment-ledger','false_friend_kits_to_avoid':'vampire-nocturne|infernal-pact','font_dice_notes':'Use restrained archival serif and ash-neutral dice; no faux-inscription inside art. Exact premium tokens INPUT REQUIRED.','kid_ok':'conditional','recipe_id':'recipe_ashen_archivist_v1','plate_delta':'light_event=grey skylight through dust; palette_pair=bone-white+ash-grey; composition_bias=layered shelves, fragments, or ruins with one verified object centered; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose archive, relic, ruin, or aftermath layouts only after definitions are supplied.','camera_family':'static_wide|macro_relic','gutter_token':'ash_deckle','role_preference':'frame_ornament>panel_tile>atmosphere_bg','negative_prompt':NEG,'kid_visual_rewrite':'Use dusty museum mystery, fossils, and old maps; remove corpses, exposed remains, nihilism, and death fixation.'},
{
'tone_id':'bright_field_guide','primary_kit_key':'merfolk-abyss','secondary_kit_keys':'wood-elf-grove|dragon-hoard','false_friend_kits_to_avoid':'undead-ossuary|infernal-pact','font_dice_notes':'Use highly legible naturalist labels in overlay and bright high-contrast dice; exact premium mapping INPUT REQUIRED.','kid_ok':'yes','recipe_id':'recipe_bright_field_guide_v1','plate_delta':'light_event=sunbeam, bioluminescent shaft, or clear reflected daylight; palette_pair=teal+coral; composition_bias=observable subject with environmental context and no invented taxonomic labels; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose discovery, specimen-distance, route, or habitat layouts after definitions are supplied.','camera_family':'macro_context|wide_observational','gutter_token':'field_note_rule','role_preference':'panel_tile>atmosphere_bg>frame_ornament','negative_prompt':NEG,'kid_visual_rewrite':'Favor friendly scale, obvious paths, and wonder; remove predation close-ups, drowning cues, and ambiguous poisonous contact.'},
{
'tone_id':'noir_case_file','primary_kit_key':'noir-crimson','secondary_kit_keys':'glass-spire|neon-protocol','false_friend_kits_to_avoid':'vampire-nocturne|infernal-pact|undead-ossuary','font_dice_notes':'Use condensed case headings only in overlay and sober body text; crimson accent must not reduce contrast. Exact premium mapping INPUT REQUIRED.','kid_ok':'conditional','recipe_id':'recipe_noir_case_file_v1','plate_delta':'light_event=venetian-blind slash or rain-reflected streetlight; palette_pair=charcoal+controlled-crimson; composition_bias=off-center clue with occluded depth but no invented suspect; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose clue, threshold, interview, or city-exterior layouts after definitions are supplied.','camera_family':'dutch_subtle|long_lens_street','gutter_token':'black_crimson','role_preference':'atmosphere_bg>frame_ornament>panel_tile','negative_prompt':NEG,'kid_visual_rewrite':'Shift from vice and violence to detective mystery; use rainy streets, footprints, and missing objects without weapons, blood, or predatory adults.'},
{
'tone_id':'fae_uncanny_tale','primary_kit_key':'fae-glamour','secondary_kit_keys':'high-elf-spire|dark-elf-umbrance','false_friend_kits_to_avoid':'vampire-nocturne|angelic-radiance','font_dice_notes':'Use elegant readable display accents only for overlay; iridescent dice require high-contrast numerals. Exact premium mapping INPUT REQUIRED.','kid_ok':'conditional','recipe_id':'recipe_fae_uncanny_tale_v1','plate_delta':'light_event=impossible dapple or twilight refraction; palette_pair=pearl-green+violet; composition_bias=beautiful symmetry with one rule-breaking detail explicitly grounded in supplied props; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose threshold, bargain, path, or mirrored-garden layouts after definitions are supplied.','camera_family':'frontal_symmetry|overhead_maze','gutter_token':'iridescent_vine','role_preference':'frame_ornament>panel_tile>atmosphere_bg','negative_prompt':NEG,'kid_visual_rewrite':'Keep wonder and harmless mischief; make bargains literal and visible, remove abduction cues, body transformation, predatory beauty, and hidden costs.'},
{
'tone_id':'hard_sf_terminal','primary_kit_key':'cyborg-chassis','secondary_kit_keys':'phosphor-terminal|neon-protocol','false_friend_kits_to_avoid':'glass-spire|angelic-radiance','font_dice_notes':'Use monospaced telemetry only in HTML/SVG overlay with tabular numerals; dice retain clear physical numerals. Exact premium tokens INPUT REQUIRED.','kid_ok':'conditional','recipe_id':'recipe_hard_sf_terminal_v1','plate_delta':'light_event=instrument glow and hard vacuum rim; palette_pair=graphite+diagnostic-cyan; composition_bias=orthogonal machinery and scale cues sourced strictly from SceneManifest; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose scan, machinery, EVA, or anomaly layouts after definitions are supplied.','camera_family':'orthographic_wide|helmet_pov','gutter_token':'terminal_grid','role_preference':'panel_tile>atmosphere_bg>frame_ornament','negative_prompt':NEG,'kid_visual_rewrite':'Use clear shapes, friendly robots, and safe mission-control stakes; remove body horror, decompression imagery, and dense unreadable instrumentation.'},
{
'tone_id':'pyoa_branching_crisis','primary_kit_key':'parchment-ledger','secondary_kit_keys':'ember-depths|merfolk-abyss','false_friend_kits_to_avoid':'fae-glamour|glass-spire','font_dice_notes':'Use direct, high-contrast action labels in overlay and conventional dice; exact pack mapping INPUT REQUIRED.','kid_ok':'yes','recipe_id':'recipe_pyoa_branching_crisis_v1','plate_delta':'light_event=single directional hazard light; palette_pair=storm-blue+signal-orange; composition_bias=first-person or shoulder view with only supplied routes and tools visible; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose fork, timerless hazard, tool, or escape layouts after definitions are supplied.','camera_family':'first_person|over_shoulder_route','gutter_token':'choice_wedge','role_preference':'panel_tile>atmosphere_bg>frame_ornament','negative_prompt':NEG,'kid_visual_rewrite':'Keep the decision urgent but not frightening; show safe distances, clear exits, and tools without injury or countdown pressure.'},
{
'tone_id':'kid_plain_stakes','primary_kit_key':'angelic-radiance','secondary_kit_keys':'wood-elf-grove|phoenix-ashrise','false_friend_kits_to_avoid':'infernal-pact|undead-ossuary|vampire-nocturne','font_dice_notes':'Use open, highly legible body type and high-contrast friendly dice; no decorative face for core instructions. Exact pack mapping INPUT REQUIRED.','kid_ok':'yes','recipe_id':'recipe_kid_plain_stakes_v1','plate_delta':'light_event=clear daylight or warm protective glow; palette_pair=sky-blue+sun-gold; composition_bias=readable foreground action, visible helper distance, and unobstructed safe route; append to Master Suffix','template_ids':'INPUT REQUIRED: memorable_plate_style_guide.md absent','template_why':'Choose discovery, teamwork, safe-challenge, or return-home layouts after definitions are supplied.','camera_family':'eye_level_clear|wide_safe_route','gutter_token':'rounded_clean','role_preference':'panel_tile>frame_ornament>atmosphere_bg','negative_prompt':NEG,'kid_visual_rewrite':'This is already the Kid layer: reject gore, adult romance, menace toward children, captivity, coercion, unreadable clutter, and false danger signals.'}
]

fields=list(rows[0].keys())
with (OUT/f'{PREFIX}tone_theme_image_matrix.csv').open('w',encoding='utf-8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=fields); w.writeheader(); w.writerows(rows)

all_kits=['wood-elf-grove','dark-elf-umbrance','high-elf-spire','dwarf-forgehall','orc-warcamp','dragon-hoard','phoenix-ashrise','cyborg-chassis','angelic-radiance','infernal-pact','undead-ossuary','fae-glamour','goblin-scrapheap','merfolk-abyss','vampire-nocturne','neon-protocol','parchment-ledger','bone-reliquary','phosphor-terminal','noir-crimson','glass-spire','ember-depths']
seen=set()
for r in rows:
    seen.add(r['primary_kit_key']); seen.update(r['secondary_kit_keys'].split('|'))
missing=sorted(set(all_kits)-seen)
if missing:
    raise SystemExit(f'Missing kit coverage: {missing}')

md=[]
md.append('# Part T3 — Theme and Image Pairing\n')
md.append('**Author:** Manus AI  \n**Evidence boundary:** The twenty-two exact kit keys and selected premium/comic rules come from the user-provided task summary. The underlying theme, template, and cost files were not attached; every detail that depends on those files is marked **INPUT REQUIRED**.\n')
md.append('> **Presentation firewall:** A theme is a cosmetic material system. A tone may suggest a default kit, but the player may override it. Art is never ledger truth. Generated pixels contain no dialogue, captions, SFX glyphs, logos, UI, or watermarks; all lettering remains HTML/SVG overlay.\n')
md.append('## T3.1 Tone-to-theme kit matrix\n')
md.append('| Tone | Primary kit | Secondary kits | False friends to avoid | Kid | Recipe |\n|---|---|---|---|---|---|')
for r in rows:
    md.append(f"| `{r['tone_id']}` | `{r['primary_kit_key']}` | `{r['secondary_kit_keys'].replace('|','`, `')}` | `{r['false_friend_kits_to_avoid'].replace('|','`, `')}` | {r['kid_ok']} | `{r['recipe_id']}` |")
md.append('\nAll twenty-two required kit keys appear at least once as a primary or secondary recommendation. The matrix is a suggestion layer only; no renderer may use kit selection as evidence for location, faction, species, inventory, weather, or quest state.\n')

md.append('## False-friend separations\n')
md.append('| Boundary | Keep distinct | Deterministic prompt cue |\n|---|---|---|\n| Vampire Nocturne vs Infernal Pact | Moonlit velvet, predatory elegance, wine-black restraint vs sulfur, brass, seals, oath heat. | If `vampire-nocturne`, forbid sulfur vents, brass seals, and magma; if `infernal-pact`, forbid velvet salon cues and moonlit aristocratic portraiture. |\n| Vampire Nocturne vs Undead Ossuary | Living nocturnal luxury vs bone, dust, burial architecture, and post-life archive. | `vampire-nocturne` requires textile and moon edge; `undead-ossuary` requires mineral/bone material and no sensual velvet emphasis. |\n| Vampire Nocturne vs Noir Crimson | Gothic interior and moonlight vs urban case-file geometry and controlled crimson signal. | `noir-crimson` requires rain/street/blind light; `vampire-nocturne` requires moon/interior/velvet. |\n| Infernal Pact vs Ember Depths | Contract, sulfur, brass, wax, and ritual obligation vs geology, magma, forge heat, and pressure. | Never use `infernal-pact` as a generic lava theme; never imply a bargain from `ember-depths`. |\n| Phosphor Terminal vs Neon Protocol vs Cyborg Chassis | Retro terminal surface vs urban network energy vs embodied machine material. | Select terminal for registrar chrome, neon for city rhythm, chassis for physical machinery. |\n| Bone Reliquary vs Undead Ossuary | Sacred object framing vs architectural burial field. | Reliquary centers one supplied object; ossuary composes space. |')

md.append('\n## T3.2 Image-prompt recipes by tone\n')
for r in rows:
    md.append(f"\n### `{r['tone_id']}`\n")
    md.append('| Component | Append-only recipe |\n|---|---|')
    for label,key in [('Memorable-plate delta','plate_delta'),('Template fit','template_ids'),('Why','template_why'),('Comic-lite camera','camera_family'),('Gutter token','gutter_token'),('Role preference','role_preference'),('Negative prompt must-includes','negative_prompt'),('Kid Mode visual rewrite','kid_visual_rewrite'),('Font/dice note','font_dice_notes')]:
        md.append(f"| {label} | {r[key].replace('|',' / ')} |")

md.append('\n## Master append contract\n')
md.append('Each `plate_delta` is appended **after** the unavailable `memorable_plate_style_guide.md` Master Suffix. Until that source is supplied, do not flatten these deltas into standalone prompts and do not assign Templates 01–20. A production prompt builder should assemble `scene_facts + character_refs + base_style_suffix + tone_delta + global_negative`, then run a deterministic entity and lettering scrub before enqueueing.\n')

md.append('## T3.3 Cost and eligibility honesty\n')
md.append('OpenRouter documents model discovery, endpoint-specific capability records, and all-or-nothing image billing.[6] A live check on 2026-08-26 found `black-forest-labs/flux.2-klein-4b` at **$0.014 per output megapixel** and `black-forest-labs/flux.2-pro` at **$0.03 per output megapixel**, with each endpoint exposing one image per request. These are point-in-time public records, not a SynapticGM contract; runtime discovery is mandatory. The missing internal cost model means turn-frequency and monthly COGS cannot be verified.\n')
md.append('| Tier | Proposed eligibility | Model policy | Suppression rules | Evidence status |\n|---|---|---|---|---|\n| Free | Sparse comic-lite; target approximately 20% of otherwise eligible memorable beats, never 20% of all turns. | PROVIDED SUMMARY: Klein 4B for comic-lite and icons. Runtime capability probe required. | Suppress thin turns, ambiguous presence, duplicate camera beat, cooldown, Kid skip, safety/repair, and queue pressure. | PROVIDED SUMMARY; exact COGS INPUT REQUIRED. |\n| Mid | Memorable plates at chapter turns, major discoveries, boss introductions, and earned aftermath; no every-turn promise. | PROVIDED SUMMARY: Flux Pro when allowed; Klein fallback may be considered only by product config. | Same gates plus account budget and latency budget. | SPECULATIVE frequency; cost model INPUT REQUIRED. |\n| High | More frequent memorable plates and optional later strip experiments, still asynchronous and gated. | Flux Pro where approved; never bind completion to the GM turn. | Same gates; no full comic treadmill. | SPECULATIVE frequency; cost model INPUT REQUIRED. |')
md.append('\n### Eligibility decision order\n')
md.append('The deterministic order is: **Kid skip → scene fact sufficiency → memorable-beat classifier → duplicate/cooldown gate → tier entitlement → budget/capacity → model capability → asynchronous enqueue**. If any gate fails, narration proceeds normally. The GM turn never waits for art, and a failed art job never rewrites or blocks StateTx.\n')
md.append('A turn is too thin when it lacks a completed or revealed beat, has fewer than two stable visual anchors, or contains unresolved presence/location ambiguity. “Alone invent risk” means the prompt would need to fabricate an actor, prop, architecture, or effect to form a coherent frame. In that case, suppress art rather than embellish.\n')
md.append('## References\n\n[6]: https://openrouter.ai/docs/guides/overview/multimodal/image-generation "Image Generation — OpenRouter Documentation"\n')
(OUT/f'{PREFIX}Part_T3_themes_images.md').write_text('\n'.join(md),encoding='utf-8')
print('Wrote phase 4 deliverables')
